import type { CourseDefinition } from '../types.js';

// ── Helper ────────────────────────────────────────────────────────────────────

function makeAcademicCourse(
  slug: string,
  title: string,
  categorySlug: string,
  ageGroup: CourseDefinition['ageGroup'],
  ageRange: string,
  type: string,
  description: string,
  imagePrompt: string,
  tags: string[],
  section1Title: string,
  lessons1: string[],
  quiz1Title: string,
  section2Title: string,
  lessons2: string[],
  quiz2Title: string,
): CourseDefinition {
  const makeLesson = (t: string, idx: number) => ({
    title: t, slug: `${slug}-lesson-${idx + 1}`, order: idx + 1,
  });
  const makeQ = (q: string) => ({ question: q, type: 'multiple_choice' as const });
  const defaultQuestions = [
    `What is the main concept covered in this section of ${title}?`,
    `Which of the following best describes a key term from this section?`,
    `How does this topic connect to real-world applications?`,
    `What is the correct definition of the highlighted term?`,
    `Which example best illustrates the concept just learned?`,
    `What would happen if the key principle was changed?`,
    `Which statement is TRUE about this topic?`,
    `How would you apply this knowledge to solve a problem?`,
  ];
  return {
    title, slug, description, excerpt: description.slice(0, 120) + '...',
    categorySlug, ageGroup, type, hasCertification: true, imagePrompt, tags,
    sections: [
      {
        title: section1Title, order: 1,
        lessons: lessons1.map((t, i) => makeLesson(t, i)),
        quizzes: [{
          title: quiz1Title, slug: `${slug}-quiz-1`,
          questions: defaultQuestions.map(makeQ),
        }],
      },
      {
        title: section2Title, order: 2,
        lessons: lessons2.map((t, i) => makeLesson(t, i + lessons1.length)),
        quizzes: [{
          title: quiz2Title, slug: `${slug}-quiz-2`,
          questions: defaultQuestions.map(makeQ),
        }],
      },
    ],
  };
}

// ── Mathematics ───────────────────────────────────────────────────────────────

export const MATHEMATICS_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'numbers-counting', 'Numbers & Counting', 'mathematics', 'juniors', '6–8', 'mathematics',
    'Explore the world of numbers through fun activities — counting, ordering, comparing, and basic number sense for young learners.',
    'Colorful numbers floating in space with stars, counting blocks, number line, flat design, bright colors, no text',
    ['maths', 'numbers', 'counting', 'juniors', 'numeracy'],
    'Counting & Number Sense',
    ['What Are Numbers?', 'Counting to 20', 'Counting to 100', 'Number Before and After', 'Comparing Numbers — More and Less', 'Ordering Numbers'],
    'Numbers & Counting Quiz 1',
    'Number Operations',
    ['Joining Groups — Addition', 'Taking Away — Subtraction', 'Doubles and Near Doubles', 'Skip Counting by 2s, 5s, 10s', 'Shapes and Patterns', 'Fun with Money — Coins'],
    'Numbers & Counting Quiz 2',
  ),
  makeAcademicCourse(
    'basic-arithmetic', 'Basic Arithmetic', 'mathematics', 'elementary', '7–9', 'mathematics',
    'Master addition, subtraction, multiplication, and division with engaging visual methods and real-life problem solving.',
    'Colorful arithmetic symbols, addition sums, multiplication table, bright flat design, no text',
    ['maths', 'arithmetic', 'addition', 'multiplication', 'elementary'],
    'Addition & Subtraction',
    ['Mental Maths Strategies', 'Column Addition', 'Column Subtraction with Regrouping', 'Word Problems — Addition & Subtraction', 'Estimating Sums and Differences', 'Number Lines and Mental Calculation'],
    'Arithmetic Quiz 1: Add & Subtract',
    'Multiplication & Division',
    ['Multiplication as Repeated Addition', 'Times Tables 2–10', 'Long Multiplication Basics', 'Division as Sharing', 'Remainders', 'Mixed Operations — Order of Operations'],
    'Arithmetic Quiz 2: Multiply & Divide',
  ),
  makeAcademicCourse(
    'fractions-decimals-percentages', 'Fractions, Decimals & Percentages', 'mathematics', 'elementary', '9–11', 'mathematics',
    'Build confidence with fractions, decimals, and percentages — converting, calculating, and applying them to everyday contexts.',
    'Fractions as pizza slices, decimal grid, percentage sign with colorful charts, flat design, no text',
    ['maths', 'fractions', 'decimals', 'percentages', 'elementary'],
    'Fractions',
    ['What Are Fractions?', 'Equivalent Fractions', 'Simplifying Fractions', 'Adding and Subtracting Fractions', 'Multiplying Fractions', 'Mixed Numbers and Improper Fractions'],
    'Fractions Quiz',
    'Decimals & Percentages',
    ['Understanding Decimals', 'Adding and Subtracting Decimals', 'Multiplying Decimals', 'Percentages — What Does % Mean?', 'Converting Between Fractions, Decimals, Percentages', 'Real-Life Applications'],
    'Decimals & Percentages Quiz',
  ),
  makeAcademicCourse(
    'geometry-measurement', 'Geometry & Measurement', 'mathematics', 'middle', '9–12', 'mathematics',
    'Explore shapes, space, and measurement — from 2D and 3D shapes to area, perimeter, volume, and angles.',
    'Geometric shapes — triangle, circle, cube — with measurement tools, colorful educational flat design, no text',
    ['maths', 'geometry', 'shapes', 'measurement', 'middle'],
    'Shapes & Angles',
    ['2D Shapes and Their Properties', 'Angles — Types and Measurement', 'Triangles — Equilateral, Isosceles, Scalene', 'Quadrilaterals and Polygons', 'Circles — Radius, Diameter, Circumference', 'Symmetry and Transformations'],
    'Shapes & Angles Quiz',
    'Measurement & 3D',
    ['Perimeter and Area', 'Area of Triangles and Circles', '3D Shapes — Prisms, Pyramids, Spheres', 'Surface Area and Volume', 'Units of Measurement — Metric and Imperial', 'Real-Life Geometry Problems'],
    'Measurement & 3D Quiz',
  ),
  makeAcademicCourse(
    'algebra-foundations', 'Algebra Foundations', 'mathematics', 'middle', '11–14', 'mathematics',
    'Introduction to algebra — variables, expressions, equations, inequalities, and graphing for confident problem solving.',
    'Algebra symbols, x and y variables, balance scales, number line, colorful flat design, no text',
    ['maths', 'algebra', 'equations', 'variables', 'middle'],
    'Expressions & Equations',
    ['Variables and Expressions', 'Simplifying Algebraic Expressions', 'Solving One-Step Equations', 'Solving Two-Step Equations', 'Linear Inequalities', 'Substitution and Formulae'],
    'Algebra Quiz 1: Equations',
    'Graphs & Functions',
    ['Coordinates and the Number Plane', 'Plotting Linear Graphs', 'Gradient and Y-Intercept', 'Simultaneous Equations', 'Factorising Simple Expressions', 'Word Problems with Algebra'],
    'Algebra Quiz 2: Graphs & Functions',
  ),
  makeAcademicCourse(
    'statistics-probability', 'Statistics & Probability', 'mathematics', 'middle', '12–15', 'mathematics',
    'Analyse data, interpret graphs, and understand probability — essential skills for the modern world.',
    'Bar chart, pie chart, scatter plot, dice, colorful data visualization, flat design, no text',
    ['maths', 'statistics', 'probability', 'data', 'middle'],
    'Statistics & Data',
    ['Collecting and Organising Data', 'Bar Charts and Histograms', 'Pie Charts and Line Graphs', 'Mean, Median, Mode, Range', 'Scatter Graphs and Correlation', 'Misleading Statistics'],
    'Statistics Quiz',
    'Probability',
    ['Probability — Basic Concepts', 'Theoretical vs Experimental Probability', 'Probability Trees', 'Independent and Dependent Events', 'Relative Frequency', 'Real-World Probability Applications'],
    'Probability Quiz',
  ),
  makeAcademicCourse(
    'advanced-algebra', 'Advanced Algebra & Functions', 'mathematics', 'secondary', '13–16', 'mathematics',
    'Deeper algebraic reasoning — quadratics, functions, transformations, and polynomials for GCSE success.',
    'Quadratic parabola, polynomial curves, function notation, colorful graphs, flat design, no text',
    ['maths', 'algebra', 'quadratics', 'functions', 'gcse', 'secondary'],
    'Quadratics & Polynomials',
    ['Expanding and Factorising Quadratics', 'Completing the Square', 'The Quadratic Formula', 'Solving Quadratic Equations', 'Cubic Polynomials Introduction', 'Polynomial Long Division'],
    'Advanced Algebra Quiz 1',
    'Functions & Transformations',
    ['Function Notation — f(x)', 'Composite and Inverse Functions', 'Transformations of Graphs', 'Exponential Functions', 'Logarithms Introduction', 'Proof and Mathematical Reasoning'],
    'Advanced Algebra Quiz 2',
  ),
  makeAcademicCourse(
    'trigonometry', 'Trigonometry', 'mathematics', 'secondary', '14–17', 'mathematics',
    'Master trigonometric ratios, identities, and graphs — essential for engineering, physics, and higher maths.',
    'Right-angled triangle, sine wave, unit circle, colorful trig functions graph, flat design, no text',
    ['maths', 'trigonometry', 'sine', 'cosine', 'gcse', 'a-level', 'secondary'],
    'Basic Trigonometry',
    ['Right-Angled Triangles — SOH CAH TOA', 'Finding Missing Sides', 'Finding Missing Angles', 'Angles of Elevation and Depression', 'Sine Rule', 'Cosine Rule'],
    'Trigonometry Quiz 1',
    'Advanced Trigonometry',
    ['The Unit Circle', 'Trigonometric Graphs — Sine, Cosine, Tangent', 'Trigonometric Identities', 'Solving Trig Equations', '3D Trigonometry', 'Applications of Trigonometry'],
    'Trigonometry Quiz 2',
  ),
  makeAcademicCourse(
    'calculus', 'Introduction to Calculus', 'mathematics', 'advanced', '16–18', 'mathematics',
    'The mathematics of change — limits, derivatives, integrals, and their applications in science and engineering.',
    'Calculus curve with tangent line, integral area, limit notation, colorful mathematical illustration, flat design, no text',
    ['maths', 'calculus', 'derivatives', 'integrals', 'a-level', 'advanced'],
    'Differential Calculus',
    ['Limits and Continuity', 'The Derivative — Definition', 'Differentiation Rules — Power, Product, Chain', 'Higher-Order Derivatives', 'Applications — Maxima and Minima', 'Related Rates'],
    'Calculus Quiz 1: Differentiation',
    'Integral Calculus',
    ['Antiderivatives and Indefinite Integrals', 'The Definite Integral — Fundamental Theorem', 'Integration Techniques', 'Area Under a Curve', 'Volumes of Revolution', 'Differential Equations Introduction'],
    'Calculus Quiz 2: Integration',
  ),
  makeAcademicCourse(
    'discrete-mathematics', 'Discrete Mathematics', 'mathematics', 'advanced', '16–18', 'mathematics',
    'Logic, sets, combinatorics, graph theory, and number theory — the mathematics that powers computer science.',
    'Logic gates, set diagrams, graph network nodes, combinatorics symbols, colorful flat design, no text',
    ['maths', 'discrete maths', 'logic', 'graph theory', 'computer science', 'advanced'],
    'Logic & Sets',
    ['Mathematical Logic — Propositions and Truth Tables', 'Set Theory — Union, Intersection, Complement', 'Functions and Relations', 'Mathematical Induction', 'Number Theory — Primes and Modular Arithmetic', 'Cryptography Basics'],
    'Discrete Maths Quiz 1',
    'Combinatorics & Graphs',
    ['Permutations and Combinations', 'Binomial Theorem', 'Graph Theory — Vertices and Edges', 'Trees and Spanning Trees', 'Algorithms on Graphs', 'Discrete Probability'],
    'Discrete Maths Quiz 2',
  ),
];

// ── Physics ───────────────────────────────────────────────────────────────────

export const PHYSICS_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'curious-about-physics', 'Curious About Physics', 'physics', 'juniors', '6–10', 'physics',
    'Discover the amazing science of forces, motion, light, and sound through experiments and wonders of the physical world.',
    'Magnet attracting iron filings, rainbow prism, bouncing ball, colorful physics experiments flat design, no text',
    ['physics', 'science', 'experiments', 'beginners', 'juniors'],
    'Forces & Motion',
    ['What is a Force?', 'Pushes and Pulls', 'Gravity — Why Things Fall', 'Magnets and Magnetism', 'Friction and Surfaces', 'Simple Machines — Levers and Pulleys'],
    'Physics Quiz 1: Forces',
    'Light, Sound & Energy',
    ['What is Light?', 'Colors of the Rainbow', 'Shadows and Reflection', 'What is Sound?', 'How Sound Travels', 'Heat and Temperature'],
    'Physics Quiz 2: Light & Sound',
  ),
  makeAcademicCourse(
    'forces-motion', 'Forces & Motion', 'physics', 'middle', '10–13', 'physics',
    'Understand Newtonian mechanics — speed, velocity, acceleration, forces, momentum, and Newton\'s three laws.',
    'Newton\'s laws diagram, motion vectors, speed-time graph, colorful physics flat design, no text',
    ['physics', 'forces', 'motion', 'newtons laws', 'middle'],
    'Motion & Speed',
    ['Distance, Speed, and Time', 'Velocity and Acceleration', 'Distance-Time Graphs', 'Speed-Time Graphs', 'Newton\'s First Law — Inertia', 'Newton\'s Second Law — F = ma'],
    'Forces & Motion Quiz 1',
    'Forces & Momentum',
    ['Newton\'s Third Law — Action-Reaction', 'Weight and Mass', 'Balanced and Unbalanced Forces', 'Momentum and Collisions', 'Work, Energy, and Power', 'Pressure and Fluid Forces'],
    'Forces & Motion Quiz 2',
  ),
  makeAcademicCourse(
    'electricity-magnetism', 'Electricity & Magnetism', 'physics', 'middle', '11–14', 'physics',
    'Explore electric circuits, current, voltage, resistance, and the fascinating link between electricity and magnetism.',
    'Electric circuit with lightbulb, voltmeter, magnetic field lines, colorful physics illustration, flat design, no text',
    ['physics', 'electricity', 'magnetism', 'circuits', 'middle'],
    'Electric Circuits',
    ['What is Electric Current?', 'Voltage and Resistance — Ohm\'s Law', 'Series and Parallel Circuits', 'Circuit Diagrams and Symbols', 'Electrical Power and Energy', 'Static Electricity'],
    'Electricity Quiz',
    'Magnetism & Electromagnetism',
    ['Magnetic Fields and Field Lines', 'The Earth as a Magnet', 'Electromagnets — How They Work', 'Motors and Generators', 'Transformers and Mains Electricity', 'Applications — MRI and Maglev Trains'],
    'Magnetism Quiz',
  ),
  makeAcademicCourse(
    'waves-light-sound', 'Waves, Light & Sound', 'physics', 'secondary', '12–15', 'physics',
    'Investigate the properties of waves — transverse and longitudinal, reflection, refraction, interference, and the electromagnetic spectrum.',
    'Wave diagrams, prism rainbow, sound wave oscilloscope, electromagnetic spectrum, colorful flat design, no text',
    ['physics', 'waves', 'light', 'sound', 'optics', 'secondary'],
    'Waves',
    ['Wave Properties — Amplitude, Wavelength, Frequency', 'Transverse and Longitudinal Waves', 'Wave Speed Equation', 'Reflection and Refraction', 'Diffraction and Interference', 'The Electromagnetic Spectrum'],
    'Waves Quiz',
    'Light & Sound',
    ['Refraction and Lenses', 'Total Internal Reflection and Optical Fibres', 'Colour and Filters', 'The Nature of Sound', 'Ultrasound Applications', 'Seismic Waves and the Earth'],
    'Light & Sound Quiz',
  ),
  makeAcademicCourse(
    'advanced-physics', 'Advanced Physics', 'physics', 'advanced', '15–18', 'physics',
    'A-Level physics covering nuclear physics, quantum mechanics, particle physics, astrophysics, and advanced mechanics.',
    'Particle collision, atom nucleus, quantum wave-particle duality, black hole, colorful advanced physics illustration, no text',
    ['physics', 'nuclear', 'quantum', 'astrophysics', 'a-level', 'advanced'],
    'Quantum & Nuclear',
    ['Atomic Models — Thomson to Bohr', 'Radioactivity — Alpha, Beta, Gamma', 'Nuclear Fission and Fusion', 'Quantum Mechanics Introduction', 'Wave-Particle Duality', 'The Photoelectric Effect'],
    'Advanced Physics Quiz 1',
    'Relativity & Astrophysics',
    ['Special Relativity — Time Dilation', 'Energy-Mass Equivalence — E = mc²', 'The Standard Model of Particle Physics', 'Stars — Life Cycle', 'Black Holes and Neutron Stars', 'The Big Bang and Cosmology'],
    'Advanced Physics Quiz 2',
  ),
];

// ── Chemistry ─────────────────────────────────────────────────────────────────

export const CHEMISTRY_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'matter-materials', 'Matter & Materials', 'chemistry', 'juniors', '6–10', 'chemistry',
    'Explore the world of materials — solids, liquids, gases, mixtures, and simple chemical changes through fun experiments.',
    'Colorful chemistry lab with glowing test tubes, bubbling beakers, molecular models, flat design, no text',
    ['chemistry', 'science', 'materials', 'states of matter', 'juniors'],
    'States of Matter',
    ['What is Matter?', 'Solids — Properties and Examples', 'Liquids — Flow and Shape', 'Gases and Air', 'Changing States — Melting and Freezing', 'Evaporation and Condensation'],
    'Matter Quiz',
    'Materials & Changes',
    ['Mixing Materials', 'Dissolving — Solutions and Solubility', 'Separating Mixtures', 'Reversible and Irreversible Changes', 'Natural vs Man-Made Materials', 'Materials Around Us — Wood, Metal, Plastic'],
    'Materials Quiz',
  ),
  makeAcademicCourse(
    'atoms-elements', 'Atoms & Elements', 'chemistry', 'middle', '10–13', 'chemistry',
    'Discover atoms, elements, the periodic table, and compounds — the fundamental building blocks of all matter.',
    'Periodic table with glowing elements, atom model with electrons, molecule bonds, colorful flat design, no text',
    ['chemistry', 'atoms', 'elements', 'periodic table', 'middle'],
    'Atoms & Elements',
    ['What Are Atoms?', 'Protons, Neutrons, and Electrons', 'Elements and the Periodic Table', 'Groups and Periods in the Periodic Table', 'Metals and Non-Metals', 'Noble Gases and Halogens'],
    'Atoms & Elements Quiz',
    'Compounds & Bonding',
    ['Molecules and Compounds', 'Chemical Formulae', 'Ionic Bonding', 'Covalent Bonding', 'Mixtures vs Pure Substances', 'Common Chemical Compounds in Daily Life'],
    'Compounds Quiz',
  ),
  makeAcademicCourse(
    'chemical-reactions', 'Chemical Reactions', 'chemistry', 'middle', '11–14', 'chemistry',
    'Understand how and why chemicals react — equations, types of reactions, acids and bases, and energy changes.',
    'Chemical reaction explosion of colors, test tubes, equation arrows, pH scale, colorful flat design, no text',
    ['chemistry', 'reactions', 'equations', 'acids', 'bases', 'middle'],
    'Reactions & Equations',
    ['Signs of a Chemical Reaction', 'Word Equations', 'Balancing Symbol Equations', 'Types of Reactions — Synthesis, Decomposition', 'Combustion and Oxidation', 'Displacement Reactions'],
    'Chemical Reactions Quiz 1',
    'Acids, Bases & Energy',
    ['Acids and Alkalis — pH Scale', 'Neutralisation Reactions', 'Reactions of Acids with Metals', 'Exothermic and Endothermic Reactions', 'Catalysts and Reaction Rates', 'Electrolysis Basics'],
    'Chemical Reactions Quiz 2',
  ),
  makeAcademicCourse(
    'organic-chemistry', 'Organic Chemistry', 'chemistry', 'secondary', '14–17', 'chemistry',
    'Explore the chemistry of carbon compounds — hydrocarbons, functional groups, polymers, and biochemistry.',
    'Carbon chain molecule, benzene ring, polymer chain, organic chemistry structures, colorful flat design, no text',
    ['chemistry', 'organic', 'hydrocarbons', 'polymers', 'secondary', 'gcse'],
    'Hydrocarbons',
    ['Introduction to Organic Chemistry', 'Alkanes and Alkenes', 'Naming Organic Compounds — IUPAC', 'Reactions of Alkenes — Addition', 'Crude Oil and Fractional Distillation', 'Cracking Hydrocarbons'],
    'Organic Chemistry Quiz 1',
    'Functional Groups & Polymers',
    ['Alcohols — Ethanol and Fermentation', 'Carboxylic Acids and Esters', 'Polymers — Addition and Condensation', 'Amino Acids and Proteins', 'DNA and Genetic Material', 'Green Chemistry and Sustainability'],
    'Organic Chemistry Quiz 2',
  ),
  makeAcademicCourse(
    'advanced-chemistry', 'Advanced Chemistry', 'chemistry', 'advanced', '15–18', 'chemistry',
    'A-Level chemistry covering thermodynamics, kinetics, equilibrium, electrochemistry, and advanced organic synthesis.',
    'Enthalpy diagram, equilibrium arrows, electrochemical cell, advanced chemistry lab, colorful flat design, no text',
    ['chemistry', 'a-level', 'thermodynamics', 'kinetics', 'equilibrium', 'advanced'],
    'Physical Chemistry',
    ['Atomic Structure and Periodicity', 'Thermodynamics — Enthalpy and Entropy', 'Kinetics — Rate Equations', 'Chemical Equilibrium — Le Chatelier\'s Principle', 'Acids and Bases — Kw and pH', 'Electrochemistry — Electrode Potentials'],
    'Advanced Chemistry Quiz 1',
    'Advanced Organic & Analytical',
    ['Reaction Mechanisms — SN1, SN2, E1, E2', 'Aromatic Chemistry — Benzene', 'Carbonyl Compounds', 'Spectroscopy — NMR, IR, Mass Spec', 'Polymer Chemistry — Nylon, Kevlar', 'Green Chemistry and Industrial Processes'],
    'Advanced Chemistry Quiz 2',
  ),
];

// ── Biology ───────────────────────────────────────────────────────────────────

export const BIOLOGY_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'animals-plants', 'Animals & Plants', 'biology', 'juniors', '6–9', 'biology',
    'Discover the living world — animals, plants, habitats, life cycles, and why every living thing is amazing.',
    'Vibrant jungle with exotic animals, flowers, butterflies, friendly nature scene, flat design, bright colors, no text',
    ['biology', 'animals', 'plants', 'nature', 'habitats', 'juniors'],
    'The Living World',
    ['Living and Non-Living Things', 'Animals Around the World', 'What Do Animals Eat? — Food Chains', 'Habitats — Where Animals Live', 'Life Cycles — Butterfly, Frog', 'Plants — Roots, Stem, Leaves, Flowers'],
    'Animals & Plants Quiz 1',
    'Growth & Survival',
    ['How Plants Make Food — Photosynthesis', 'Seeds and How Plants Grow', 'Seasons and Nature', 'Taking Care of Our World', 'Endangered Animals', 'Pets and Domestic Animals'],
    'Animals & Plants Quiz 2',
  ),
  makeAcademicCourse(
    'human-body', 'The Human Body', 'biology', 'elementary', '8–12', 'biology',
    'Explore the incredible human body — organs, systems, nutrition, exercise, and how to stay healthy.',
    'Human body diagram with colorful organs, skeleton, healthy food, flat design for kids, no text',
    ['biology', 'human body', 'organs', 'health', 'elementary'],
    'Body Systems Part 1',
    ['Cells — The Building Blocks of Life', 'The Skeleton and Muscles', 'The Digestive System', 'The Circulatory System — Heart and Blood', 'The Respiratory System — Lungs', 'The Nervous System — Brain and Nerves'],
    'Human Body Quiz 1',
    'Health & Nutrition',
    ['Nutrition — Proteins, Carbs, Fats, Vitamins', 'Healthy Eating — The Food Plate', 'Exercise and Fitness', 'The Immune System and Fighting Illness', 'The Reproductive System — Life Cycle', 'Mental Health and Wellbeing'],
    'Human Body Quiz 2',
  ),
  makeAcademicCourse(
    'cells-microorganisms', 'Cells & Microorganisms', 'biology', 'middle', '10–14', 'biology',
    'Go microscopic! Explore cell structure, prokaryotes, eukaryotes, bacteria, viruses, and the microscopic world.',
    'Colorful cell diagram with organelles, bacteria, virus, microscope, flat design, no text',
    ['biology', 'cells', 'microorganisms', 'bacteria', 'viruses', 'middle'],
    'Cell Biology',
    ['Animal and Plant Cells — Structure', 'Cell Organelles — Nucleus, Mitochondria', 'Cell Membranes and Transport', 'Cell Division — Mitosis', 'Prokaryotic vs Eukaryotic Cells', 'Specialised Cells'],
    'Cells Quiz',
    'Microorganisms',
    ['Bacteria — Types and Functions', 'Viruses — How They Work', 'Fungi and Protists', 'Infectious Diseases', 'The Immune System in Detail', 'Microorganisms — Beneficial Uses'],
    'Microorganisms Quiz',
  ),
  makeAcademicCourse(
    'genetics-dna', 'Genetics & DNA', 'biology', 'secondary', '13–16', 'biology',
    'Uncover the secrets of DNA, heredity, evolution, and the biotechnology revolution shaping medicine and science.',
    'DNA double helix, chromosome, inheritance diagram, genetic engineering tools, colorful flat design, no text',
    ['biology', 'genetics', 'dna', 'heredity', 'evolution', 'secondary'],
    'Genetics',
    ['DNA Structure and Function', 'Chromosomes and Genes', 'Cell Division — Meiosis', 'Mendelian Genetics — Dominant and Recessive', 'Punnett Squares and Inheritance', 'Mutations and Genetic Variation'],
    'Genetics Quiz',
    'Evolution & Biotechnology',
    ['Natural Selection and Evolution', 'Darwin\'s Theory of Evolution', 'Evidence for Evolution', 'Classification of Living Things', 'Genetic Engineering and Cloning', 'Biotechnology — GM Crops, Medicine'],
    'Evolution & Biotechnology Quiz',
  ),
  makeAcademicCourse(
    'ecology-environment', 'Ecology & Environment', 'biology', 'middle', '12–16', 'biology',
    'Study ecosystems, food webs, biodiversity, and the impact of human activity on our natural world.',
    'Ecosystem with forest, river, animals, food web arrows, biodiversity chart, colorful flat design, no text',
    ['biology', 'ecology', 'ecosystems', 'biodiversity', 'environment', 'middle'],
    'Ecosystems',
    ['Ecosystems — Biotic and Abiotic Factors', 'Food Webs and Energy Flow', 'Nutrient Cycles — Carbon and Nitrogen', 'Population Dynamics', 'Biodiversity and Biomes', 'Adaptations to Environments'],
    'Ecology Quiz 1',
    'Human Impact',
    ['Human Population Growth', 'Pollution — Air, Water, Soil', 'Deforestation and Habitat Loss', 'Climate Change and Ecosystems', 'Conservation and Endangered Species', 'Sustainable Development'],
    'Ecology Quiz 2',
  ),
  makeAcademicCourse(
    'advanced-biology-biotechnology', 'Advanced Biology & Biotechnology', 'biology', 'advanced', '15–18', 'biology',
    'A-Level biology — cell biology, biochemistry, physiology, genetics, and cutting-edge biotechnology.',
    'Advanced cell biology, protein synthesis, neuron, biotech lab equipment, colorful scientific flat design, no text',
    ['biology', 'a-level', 'biochemistry', 'physiology', 'biotechnology', 'advanced'],
    'Advanced Molecular Biology',
    ['Biochemistry — Proteins, Enzymes, Lipids', 'Cell Respiration — Glycolysis, Krebs', 'Photosynthesis in Depth', 'Protein Synthesis — Transcription, Translation', 'Regulation of Gene Expression', 'Cancer Biology'],
    'Advanced Biology Quiz 1',
    'Physiology & Biotechnology',
    ['Neurophysiology — Action Potentials', 'Hormonal Control — Endocrine System', 'Homeostasis — Thermoregulation, Osmoregulation', 'Plant Physiology — Hormones and Tropisms', 'Immunology — Antibodies and Vaccines', 'CRISPR and Gene Editing'],
    'Advanced Biology Quiz 2',
  ),
];

// ── Earth & Space Sciences ────────────────────────────────────────────────────

export const EARTH_SPACE_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'our-planet-earth', 'Our Planet Earth', 'earth-space-sciences', 'juniors', '6–10', 'earth-science',
    'Journey through our amazing planet — continents, oceans, mountains, volcanoes, and the wonders of nature.',
    'Beautiful planet Earth with mountains, oceans, volcanoes, trees, bright flat design, no text',
    ['earth science', 'geography', 'nature', 'planets', 'juniors'],
    'Our Planet',
    ['Planet Earth — Shape and Size', 'Continents and Oceans', 'Land and Water', 'Mountains, Valleys, and Plains', 'Rocks and Minerals', 'Volcanoes and Earthquakes'],
    'Earth Quiz 1',
    'Seasons & Natural Wonders',
    ['Day and Night', 'The Seasons', 'The Water Cycle', 'Weather — Sun, Rain, Wind, Snow', 'Ecosystems — Rainforest, Desert, Arctic', 'Taking Care of Earth'],
    'Earth Quiz 2',
  ),
  makeAcademicCourse(
    'weather-climate', 'Weather & Climate', 'earth-space-sciences', 'elementary', '8–12', 'earth-science',
    'Explore weather patterns, climate zones, the atmosphere, and how weather affects people and ecosystems.',
    'Weather symbols — sun, clouds, rain, snow — climate map, atmosphere layers, flat design, no text',
    ['earth science', 'weather', 'climate', 'atmosphere', 'elementary'],
    'Weather',
    ['The Atmosphere — Layers', 'Weather vs Climate', 'Wind and Pressure Systems', 'Clouds and Precipitation', 'Extreme Weather — Storms, Hurricanes', 'Weather Forecasting and Instruments'],
    'Weather Quiz',
    'Climate',
    ['Climate Zones — Tropical, Temperate, Polar', 'Biomes and Climate', 'Ocean Currents and Climate', 'El Niño and La Niña', 'The Greenhouse Effect', 'Climate Change — Evidence and Effects'],
    'Climate Quiz',
  ),
  makeAcademicCourse(
    'astronomy-space', 'Astronomy & Space', 'earth-space-sciences', 'middle', '10–14', 'earth-science',
    'Explore the cosmos — our solar system, stars, galaxies, space exploration, and the mysteries of the universe.',
    'Solar system planets, stars, galaxy, rocket ship, telescope, colorful space illustration flat design, no text',
    ['astronomy', 'space', 'planets', 'solar system', 'stars', 'middle'],
    'Our Solar System',
    ['The Solar System — Overview', 'The Sun — Our Star', 'The Inner Planets — Mercury to Mars', 'The Outer Planets — Jupiter to Neptune', 'Moons, Asteroids, and Comets', 'Space Exploration — Missions and Rovers'],
    'Solar System Quiz',
    'Stars & Universe',
    ['How Stars Form and Die', 'Types of Stars — Main Sequence, Red Giants', 'Our Galaxy — The Milky Way', 'Galaxies — Types and Formation', 'The Big Bang Theory', 'Black Holes and Neutron Stars'],
    'Stars & Universe Quiz',
  ),
  makeAcademicCourse(
    'environmental-science', 'Environmental Science', 'earth-space-sciences', 'secondary', '12–16', 'earth-science',
    'Study Earth\'s systems, natural resources, pollution, biodiversity, and the science behind environmental challenges.',
    'Earth systems diagram, carbon cycle, pollution effects, renewable energy, colorful flat design, no text',
    ['earth science', 'environment', 'ecology', 'sustainability', 'secondary'],
    'Earth Systems',
    ['Earth\'s Systems — Geosphere, Hydrosphere, Atmosphere, Biosphere', 'Biogeochemical Cycles — Carbon, Nitrogen, Water', 'Natural Resources — Renewable and Non-Renewable', 'Soil Science and Land Use', 'Oceanography Basics', 'Natural Hazards — Earthquakes, Floods, Wildfires'],
    'Environmental Science Quiz 1',
    'Human Impact & Sustainability',
    ['Air Pollution and Health', 'Water Pollution and Management', 'Waste and Recycling', 'Biodiversity Loss and Conservation', 'Deforestation and Land Use Change', 'Sustainable Development Goals'],
    'Environmental Science Quiz 2',
  ),
  makeAcademicCourse(
    'climate-change-solutions', 'Climate Change & Solutions', 'earth-space-sciences', 'secondary', '13–18', 'earth-science',
    'Understand the science, impacts, and solutions of climate change — from renewable energy to global policy and activism.',
    'Earth with rising temperature graph, solar panels, wind turbines, ice caps, colorful flat design, no text',
    ['climate change', 'renewable energy', 'sustainability', 'environment', 'secondary'],
    'Climate Science',
    ['The Climate System', 'Historical Climate Change', 'Greenhouse Gases — Sources and Sinks', 'Climate Models and Predictions', 'Impacts — Sea Level Rise, Extreme Weather', 'Tipping Points and Feedback Loops'],
    'Climate Change Quiz 1',
    'Solutions & Action',
    ['Renewable Energy — Solar, Wind, Hydro', 'Energy Efficiency and Conservation', 'Carbon Capture and Storage', 'International Climate Policy — Paris Agreement', 'Individual Actions vs System Change', 'Youth Climate Activism'],
    'Climate Change Quiz 2',
  ),
];

// ── History ───────────────────────────────────────────────────────────────────

export const HISTORY_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'stories-from-the-past', 'Stories from the Past', 'history', 'juniors', '6–9', 'history',
    'Travel through time and discover amazing stories — great inventions, brave explorers, and how people lived long ago.',
    'Timeline with castles, pyramids, ships, and colorful historical artifacts in a journey through time, flat design, no text',
    ['history', 'stories', 'past', 'juniors', 'primary'],
    'Long, Long Ago',
    ['How Do We Know About the Past?', 'Stone Age — Cave People', 'Ancient Egypt — Pharaohs and Pyramids', 'Ancient Greece — Gods and Heroes', 'Ancient Rome — Gladiators and Emperors', 'The Vikings — Raiders and Explorers'],
    'History Quiz 1: Ancient World',
    'Great People & Inventions',
    ['Inventions That Changed the World', 'Famous Explorers and Discoveries', 'Heroes of History', 'Castles, Knights, and the Middle Ages', 'How People Lived 100 Years Ago', 'History in My Community'],
    'History Quiz 2: People & Change',
  ),
  makeAcademicCourse(
    'ancient-civilizations', 'Ancient Civilizations', 'history', 'elementary', '8–12', 'history',
    'Explore the world\'s great ancient civilizations — Egypt, Greece, Rome, Mesopotamia, India, and China.',
    'Pyramids, Greek temple, Roman Colosseum, Great Wall, Indus Valley city, colorful historical illustration, flat design, no text',
    ['history', 'ancient history', 'civilizations', 'egypt', 'rome', 'greece', 'elementary'],
    'First Civilizations',
    ['Mesopotamia — Cradle of Civilization', 'Ancient Egypt — Society and Culture', 'The Indus Valley Civilization', 'Ancient China — Dynasties and Inventions', 'Ancient Greece — Democracy and Philosophy', 'The Persian Empire'],
    'Ancient Civilizations Quiz 1',
    'Rome & The Americas',
    ['The Roman Republic and Empire', 'Roman Culture and Legacy', 'The Byzantine Empire', 'The Maya Civilization', 'The Aztec Empire', 'The Inca Empire'],
    'Ancient Civilizations Quiz 2',
  ),
  makeAcademicCourse(
    'medieval-world', 'The Medieval World', 'history', 'middle', '10–13', 'history',
    'Explore the Middle Ages — feudal society, the Crusades, the Black Death, and the rise of nation-states.',
    'Medieval castle, knights in armor, cathedral, feudal system diagram, colorful flat design, no text',
    ['history', 'medieval', 'feudalism', 'crusades', 'middle ages', 'middle'],
    'Feudal Society',
    ['The Fall of the Roman Empire', 'The Rise of Feudalism', 'Life in a Medieval Castle', 'The Role of the Church in Medieval Europe', 'The Crusades', 'Islamic Golden Age'],
    'Medieval World Quiz 1',
    'Change & Transition',
    ['The Black Death — Causes and Consequences', 'Magna Carta and the Birth of Rights', 'The Mongol Empire', 'Japan in the Medieval Period', 'The Hundred Years\' War', 'Late Middle Ages — Change and Transition'],
    'Medieval World Quiz 2',
  ),
  makeAcademicCourse(
    'age-of-exploration', 'The Age of Exploration', 'history', 'middle', '10–13', 'history',
    'Discover the era of explorers — Columbus, da Gama, Magellan — and the profound consequences of European expansion.',
    'Sailing ship on ocean, old world map, compass, explorer with telescope, colorful flat design, no text',
    ['history', 'exploration', 'columbus', 'age of discovery', 'middle'],
    'The Great Explorers',
    ['Why Did Europeans Explore?', 'Portuguese Exploration — Henry the Navigator', 'Columbus and the Americas', 'Vasco da Gama and the Route to India', 'Magellan\'s Circumnavigation', 'John Cabot and the Northern Route'],
    'Exploration Quiz 1',
    'Consequences & Colonialism',
    ['The Spanish Conquistadors — Cortés and Pizarro', 'The Columbian Exchange', 'The Transatlantic Slave Trade', 'The Rise of Colonialism', 'Impact on Indigenous Peoples', 'Legacy of the Age of Exploration'],
    'Exploration Quiz 2',
  ),
  makeAcademicCourse(
    'industrial-revolution', 'The Industrial Revolution', 'history', 'middle', '11–14', 'history',
    'Explore how industrialisation transformed the world — steam power, factories, urbanisation, and social change.',
    'Steam engine, factory chimneys, industrial city, workers, Victorian era illustration, colorful flat design, no text',
    ['history', 'industrial revolution', 'steam engine', 'victorian', 'middle'],
    'The Rise of Industry',
    ['Why Britain? — Origins of the Industrial Revolution', 'The Steam Engine — Watt and Innovation', 'Factories and Child Labour', 'Railways — Changing the World', 'The Textile Industry', 'Agricultural Revolution'],
    'Industrial Revolution Quiz 1',
    'Society & Reform',
    ['Life in Industrial Cities', 'The Reform Movement', 'Trade Unions and Workers\' Rights', 'The British Empire During Industrialisation', 'Global Spread of Industrialisation', 'Legacy of the Industrial Revolution'],
    'Industrial Revolution Quiz 2',
  ),
  makeAcademicCourse(
    'world-wars-20th-century', 'World Wars & the 20th Century', 'history', 'secondary', '12–16', 'history',
    'A study of the First and Second World Wars, the Holocaust, the Cold War, and the major events of the 20th century.',
    'WWI trenches, WWII timeline, Cold War map, flags of nations, colorful educational flat design, no text',
    ['history', 'world war 1', 'world war 2', 'holocaust', 'cold war', 'secondary'],
    'The World Wars',
    ['Causes of World War I', 'Life in the Trenches — WWI', 'The Russian Revolution', 'The Peace of Paris — Consequences', 'Rise of Fascism and Nazism', 'Causes of World War II'],
    'World Wars Quiz 1',
    'Cold War & Modern Era',
    ['The Holocaust — Genocide and Memory', 'WWII — Key Events and Turning Points', 'The Cold War — USA vs USSR', 'Decolonisation in Africa and Asia', 'The Civil Rights Movement', 'The End of the Cold War and Globalisation'],
    'World Wars Quiz 2',
  ),
  makeAcademicCourse(
    'modern-world-history', 'Modern World History', 'history', 'secondary', '13–17', 'history',
    'Analyse the post-1945 world — decolonisation, the Cold War, globalisation, and contemporary global challenges.',
    'World map with post-war events, modern skyline, UN building, globe, colorful flat design, no text',
    ['history', 'modern history', 'globalisation', 'decolonisation', 'secondary'],
    'Post-War World',
    ['The United Nations and International Order', 'The Arab-Israeli Conflict', 'The Vietnam War', 'China\'s Rise — Mao to Modern Era', 'The Space Race', 'The Struggle Against Apartheid'],
    'Modern History Quiz 1',
    'Contemporary World',
    ['The Fall of the Berlin Wall', 'The Rwandan Genocide', '9/11 and the War on Terror', 'The Arab Spring', 'Rise of China as a Global Power', 'Globalisation, Migration, and Identity'],
    'Modern History Quiz 2',
  ),
  makeAcademicCourse(
    'history-science-invention', 'History of Science & Invention', 'history', 'middle', '10–15', 'history',
    'Trace humanity\'s greatest discoveries — from ancient astronomy to the internet — and the thinkers who changed everything.',
    'Timeline of inventions, lightbulb, telescope, DNA, computer, colorful flat design, no text',
    ['history', 'science history', 'inventions', 'discoveries', 'middle'],
    'Ancient to Renaissance Science',
    ['Ancient Astronomy — Greek and Islamic', 'The Scientific Revolution', 'Galileo, Copernicus, and Newton', 'The Age of Enlightenment', 'The Industrial Age of Invention', 'Darwin and the Theory of Evolution'],
    'History of Science Quiz 1',
    'Modern Science & Technology',
    ['Einstein and the Theory of Relativity', 'The Discovery of DNA', 'The Space Age', 'The Computer Revolution', 'The Internet and Information Age', 'Biotech, AI, and the Future'],
    'History of Science Quiz 2',
  ),
  makeAcademicCourse(
    'history-art-culture', 'History of Art & Culture', 'history', 'secondary', '12–16', 'history',
    'Explore art movements, cultural revolutions, and the social contexts that shaped human expression throughout history.',
    'Renaissance painting, impressionist brushstrokes, modern art, cultural artifacts, colorful flat design, no text',
    ['history', 'art history', 'culture', 'renaissance', 'secondary'],
    'From Ancient to Renaissance',
    ['Art in the Ancient World', 'Medieval and Byzantine Art', 'The Italian Renaissance — Leonardo, Michelangelo', 'Northern Renaissance', 'The Reformation and Its Cultural Impact', 'Baroque Art and Architecture'],
    'Art History Quiz 1',
    'Modern to Contemporary',
    ['Romanticism and Realism', 'Impressionism — Monet, Renoir, Degas', 'Modernism — Picasso and Cubism', 'The Harlem Renaissance', 'Postmodernism and Contemporary Art', 'Global Art Traditions'],
    'Art History Quiz 2',
  ),
  makeAcademicCourse(
    'postcolonial-history', 'Postcolonial History & Perspectives', 'history', 'advanced', '15–18', 'history',
    'Critical examination of colonialism, empire, decolonisation, and their lasting impacts on societies worldwide.',
    'World map showing former colonial empires, independence flags, protest movements, colorful flat design, no text',
    ['history', 'postcolonial', 'decolonisation', 'empire', 'advanced', 'a-level'],
    'Empire & Colonialism',
    ['Theories of Colonialism and Imperialism', 'The British Empire — Rise and Rule', 'French, Dutch, and Belgian Colonialism', 'The Scramble for Africa', 'Colonial Rule — Resistance and Collaboration', 'The First World War and Colonialism'],
    'Postcolonial History Quiz 1',
    'Decolonisation & Legacy',
    ['Indian Independence — Gandhi and Partition', 'African Independence Movements', 'Caribbean and Pacific Decolonisation', 'Postcolonial Theory — Said, Fanon, Spivak', 'Racism, Identity, and Legacy of Empire', 'Reparations and Memory'],
    'Postcolonial History Quiz 2',
  ),
];

// ── Geography ─────────────────────────────────────────────────────────────────

export const GEOGRAPHY_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'countries-continents', 'My World: Countries & Continents', 'geography', 'juniors', '6–10', 'geography',
    'Explore our amazing world — the seven continents, oceans, countries, capitals, and incredible places on Earth.',
    'Colorful world map with continents, flags, animals, compass rose, flat design, no text',
    ['geography', 'world', 'continents', 'countries', 'juniors'],
    'Continents & Oceans',
    ['The Seven Continents', 'The Five Oceans', 'Maps and Globes', 'Africa — Countries and Landmarks', 'Asia — Countries and Cultures', 'The Americas — North and South'],
    'Continents Quiz',
    'Europe, Oceania & Poles',
    ['Europe — Countries and Capitals', 'Oceania — Australia, New Zealand, Pacific', 'The Arctic and Antarctica', 'World Records — Largest, Longest, Highest', 'Flags of the World', 'My Country in the World'],
    'Countries Quiz',
  ),
  makeAcademicCourse(
    'physical-geography', 'Physical Geography', 'geography', 'middle', '9–13', 'geography',
    'Study Earth\'s physical features — landforms, rivers, coasts, glaciers, weathering, and the forces that shape our planet.',
    'Mountains, rivers, glaciers, tectonic plates, coastal erosion, colorful geographical flat design, no text',
    ['geography', 'physical geography', 'landforms', 'rivers', 'coasts', 'middle'],
    'Landforms & Processes',
    ['Plate Tectonics and Continental Drift', 'Volcanoes — Types and Formation', 'Earthquakes — Causes and Effects', 'River Processes — Erosion, Transport, Deposition', 'River Landforms — Waterfalls, Oxbow Lakes', 'Coastal Processes and Landforms'],
    'Physical Geography Quiz 1',
    'Ice & Weathering',
    ['Glaciation — Glaciers and Ice Ages', 'Glacial Landforms — U-Valleys, Moraines', 'Weathering — Chemical, Physical, Biological', 'Mass Movement — Landslides', 'Soil Formation and Types', 'Biomes and Climate Relationships'],
    'Physical Geography Quiz 2',
  ),
  makeAcademicCourse(
    'human-geography', 'Human Geography', 'geography', 'middle', '10–14', 'geography',
    'Explore how humans interact with places — urbanisation, migration, development, culture, and global connections.',
    'City skyline, migration arrows on map, development indicators, diverse cultures, flat design, no text',
    ['geography', 'human geography', 'urbanisation', 'migration', 'development', 'middle'],
    'Population & Migration',
    ['World Population — Distribution and Density', 'Population Growth and Demographic Transition', 'Migration — Types, Causes, Effects', 'Urbanisation — Growth of Cities', 'Megacities — Opportunities and Challenges', 'Rural Settlement Patterns'],
    'Human Geography Quiz 1',
    'Development & Culture',
    ['Measuring Development — HDI, GDP', 'Economic Development — Trade and Aid', 'Tourism — Impacts and Management', 'Cultural Landscapes — Language, Religion', 'Globalisation — Causes and Impacts', 'Fair Trade and Economic Justice'],
    'Human Geography Quiz 2',
  ),
  makeAcademicCourse(
    'environmental-geography', 'Environmental Geography', 'geography', 'secondary', '11–15', 'geography',
    'Investigate the relationships between human activity and the natural environment — sustainability, climate, and conservation.',
    'Human-nature interaction, deforestation, clean energy, natural disasters, sustainability symbols, flat design, no text',
    ['geography', 'environment', 'sustainability', 'climate', 'secondary'],
    'Natural Hazards',
    ['Tectonic Hazards — Living with Earthquakes and Volcanoes', 'Tropical Storms — Formation and Management', 'Flooding — Causes, Effects, Responses', 'Drought and Famine', 'Wildfires — Increasing Risk', 'Hazard Risk and Vulnerability'],
    'Environmental Geography Quiz 1',
    'Sustainability & Climate',
    ['Climate Change — Causes and Evidence', 'Climate Change Impacts on Geography', 'Ecosystem Services and Biodiversity', 'Sustainable Resource Management — Water, Food', 'Energy — Fossil Fuels vs Renewables', 'Sustainable Cities of the Future'],
    'Environmental Geography Quiz 2',
  ),
  makeAcademicCourse(
    'economic-geography', 'Economic Geography', 'geography', 'secondary', '13–17', 'geography',
    'Analyse the geography of economic activity — industry, trade, TNCs, economic development, and uneven development.',
    'World trade routes, factory locations, economic data map, supply chain, colorful flat design, no text',
    ['geography', 'economic geography', 'trade', 'development', 'secondary'],
    'Economic Activity',
    ['Primary, Secondary, Tertiary, Quaternary Sectors', 'Location of Industry — Factors', 'Transnational Corporations — TNCs', 'Deindustrialisation and Decline', 'Service Industries and Technology', 'Economic Clusters — Silicon Valley'],
    'Economic Geography Quiz 1',
    'Trade & Development',
    ['International Trade — Patterns and Players', 'Free Trade vs Protectionism', 'Uneven Development — Causes', 'Strategies for Development — Top-Down, Bottom-Up', 'Emerging Economies — BRICS', 'The Role of Aid and NGOs'],
    'Economic Geography Quiz 2',
  ),
  makeAcademicCourse(
    'geopolitics-world-affairs', 'Geopolitics & World Affairs', 'geography', 'advanced', '15–18', 'geography',
    'Understand global power, borders, conflict, international organisations, and the geopolitical forces shaping the world.',
    'World map with geopolitical zones, UN headquarters, conflict zones, power dynamics, colorful flat design, no text',
    ['geography', 'geopolitics', 'international relations', 'global affairs', 'advanced'],
    'Power & Borders',
    ['What is Geopolitics?', 'Nation-States, Sovereignty, and Borders', 'Global Superpowers — USA, China, Russia', 'The Rise of China', 'The European Union — Integration and Tensions', 'Cold War Geopolitics to Today'],
    'Geopolitics Quiz 1',
    'Conflict & Governance',
    ['Causes of Conflict — Resources, Identity', 'Case Study: A Regional Conflict', 'The United Nations and Peacekeeping', 'Refugees and Humanitarian Crisis', 'Nuclear Weapons and Arms Control', 'The Future of Global Governance'],
    'Geopolitics Quiz 2',
  ),
];

// ── Social Studies & Civics ───────────────────────────────────────────────────

export const SOCIAL_STUDIES_COURSES: CourseDefinition[] = [
  makeAcademicCourse(
    'community-society', 'Community & Society', 'social-studies-civics', 'juniors', '6–10', 'social-studies',
    'Understand our community — roles, responsibilities, local government, cultural diversity, and how we live together.',
    'Diverse children from different cultures, community buildings, local government, flat design, no text',
    ['social studies', 'community', 'civics', 'diversity', 'juniors'],
    'Our Community',
    ['What is a Community?', 'People Who Help Us — Community Workers', 'Rules and Why We Need Them', 'My School Community', 'Local Government — Who Makes Decisions?', 'Neighbourhoods — Urban, Suburban, Rural'],
    'Community Quiz',
    'Diversity & Responsibility',
    ['Cultures in My Community', 'Celebrating Diversity', 'Rights and Responsibilities', 'Being a Good Citizen', 'How We Can Help Our Community', 'Our World Community'],
    'Society Quiz',
  ),
  makeAcademicCourse(
    'government-democracy', 'Government & Democracy', 'social-studies-civics', 'middle', '10–14', 'social-studies',
    'Learn how governments work — democracy, elections, parliament, the constitution, and civic participation.',
    'Parliament building, voting ballot box, constitution scroll, flags, diverse citizens, flat design, no text',
    ['civics', 'government', 'democracy', 'elections', 'middle'],
    'Democratic Government',
    ['Types of Government — Democracy, Monarchy, Republic', 'How Parliament or Congress Works', 'Elections and Voting', 'The Role of the Head of State', 'Separation of Powers', 'The UK Constitution vs US Constitution'],
    'Government Quiz 1',
    'Rights & Citizenship',
    ['Human Rights — Universal Declaration', 'Civil Rights and Freedoms', 'The Rule of Law', 'Political Parties and Ideology', 'Media and Democracy', 'Active Citizenship — How to Make a Difference'],
    'Government Quiz 2',
  ),
  makeAcademicCourse(
    'economics-basics', 'Economics Basics', 'social-studies-civics', 'middle', '11–14', 'social-studies',
    'Introduction to economic thinking — supply, demand, markets, money, and how economies work.',
    'Market stall, supply demand graph, coins and notes, factory and shop, colorful flat design, no text',
    ['economics', 'markets', 'supply and demand', 'money', 'middle'],
    'Markets & Money',
    ['What is Economics?', 'Needs and Wants — Scarcity and Choice', 'Supply and Demand', 'Markets and Prices', 'Money — History and Function', 'Banks and Financial Institutions'],
    'Economics Basics Quiz 1',
    'Business & Trade',
    ['Businesses — Sole Traders to Corporations', 'Profit, Loss, and Revenue', 'Trade — Local, National, International', 'Imports and Exports', 'Taxes and Government Revenue', 'Economic Systems — Capitalism, Mixed Economy'],
    'Economics Basics Quiz 2',
  ),
  makeAcademicCourse(
    'global-economics', 'Global Economics', 'social-studies-civics', 'advanced', '14–18', 'social-studies',
    'Explore the global economy — international trade, multinational corporations, development, and inequality.',
    'Global trade map, multinational logos, development chart, world inequality, colorful flat design, no text',
    ['economics', 'globalisation', 'trade', 'development', 'advanced'],
    'The Global Economy',
    ['Globalisation — What Does It Mean?', 'International Trade — WTO and Agreements', 'Multinational Corporations', 'Foreign Direct Investment', 'Exchange Rates and Currency', 'Balance of Payments'],
    'Global Economics Quiz 1',
    'Development & Inequality',
    ['Measuring Development — GDP, HDI, Gini', 'The Poverty Trap', 'Aid vs Trade — Which Helps More?', 'The IMF and World Bank', 'Sustainable Development Goals', 'Inequality Within and Between Countries'],
    'Global Economics Quiz 2',
  ),
  makeAcademicCourse(
    'law-justice', 'Law & Justice', 'social-studies-civics', 'secondary', '13–18', 'social-studies',
    'Explore the legal system — criminal and civil law, rights, the courts, and principles of justice.',
    'Scales of justice, courtroom, gavel, law books, constitution, colorful flat design, no text',
    ['law', 'justice', 'courts', 'rights', 'secondary'],
    'The Legal System',
    ['What is Law? — Purpose and Types', 'Criminal vs Civil Law', 'How a Court Case Works', 'The Jury System', 'Sentencing and Justice', 'Human Rights Law'],
    'Law & Justice Quiz 1',
    'Justice & Society',
    ['Youth Justice — How Young People Are Treated', 'Miscarriages of Justice', 'International Law — War Crimes', 'Alternative Dispute Resolution', 'Justice and Equality', 'Future of Law — AI and Technology'],
    'Law & Justice Quiz 2',
  ),
  makeAcademicCourse(
    'human-rights-global-issues', 'Human Rights & Global Issues', 'social-studies-civics', 'advanced', '14–18', 'social-studies',
    'Study human rights, global challenges, and the organisations working to create a fairer world.',
    'Human rights symbols, diverse people, UN declaration, global challenges icons, colorful flat design, no text',
    ['human rights', 'global issues', 'un', 'advocacy', 'advanced'],
    'Human Rights',
    ['Universal Declaration of Human Rights — History', 'Civil and Political Rights', 'Economic, Social, Cultural Rights', 'Childrens Rights — UNCRC', 'Gender Equality and Women\'s Rights', 'LGBTQ+ Rights Around the World'],
    'Human Rights Quiz 1',
    'Global Challenges',
    ['Poverty and Global Inequality', 'Refugees and Asylum Seekers', 'Climate Justice', 'Food Security and Hunger', 'Global Health — Pandemics', 'Youth Activism and Global Change'],
    'Human Rights Quiz 2',
  ),
];

// ── Combined Export ───────────────────────────────────────────────────────────

export const ACADEMIC_COURSES: CourseDefinition[] = [
  ...MATHEMATICS_COURSES,
  ...PHYSICS_COURSES,
  ...CHEMISTRY_COURSES,
  ...BIOLOGY_COURSES,
  ...EARTH_SPACE_COURSES,
  ...HISTORY_COURSES,
  ...GEOGRAPHY_COURSES,
  ...SOCIAL_STUDIES_COURSES,
];
