import type { CourseDefinition } from '../types.js';

function makeHumanitiesCourse(
  slug: string, title: string, categorySlug: string,
  ageGroup: CourseDefinition['ageGroup'], ageRange: string, type: string,
  description: string, imagePrompt: string, tags: string[],
  s1Title: string, lessons1: string[], q1: string,
  s2Title: string, lessons2: string[], q2: string,
): CourseDefinition {
  const mkL = (t: string, i: number) => ({ title: t, slug: `${slug}-lesson-${i + 1}`, order: i + 1 });
  const mkQ = (q: string) => ({ question: q, type: 'multiple_choice' as const });
  const dqs = [
    `What is the main idea of this section?`, `Which best describes the key term covered here?`,
    `How does this topic connect to wider themes?`, `What is the correct definition of the highlighted concept?`,
    `Which example best illustrates the idea just explored?`, `What would be most appropriate in this context?`,
    `Which statement about this topic is TRUE?`, `How would you apply this skill or knowledge?`,
  ];
  return {
    title, slug, description, excerpt: description.slice(0, 120) + '...',
    categorySlug, ageGroup, type, hasCertification: true, imagePrompt, tags,
    sections: [
      { title: s1Title, order: 1, lessons: lessons1.map((t, i) => mkL(t, i)), quizzes: [{ title: q1, slug: `${slug}-quiz-1`, questions: dqs.map(mkQ) }] },
      { title: s2Title, order: 2, lessons: lessons2.map((t, i) => mkL(t, i + lessons1.length)), quizzes: [{ title: q2, slug: `${slug}-quiz-2`, questions: dqs.map(mkQ) }] },
    ],
  };
}

// ── English Language & Literature ─────────────────────────────────────────────

export const ENGLISH_LIT_COURSES: CourseDefinition[] = [
  makeHumanitiesCourse(
    'phonics-early-reading', 'Phonics & Early Reading', 'english-literature', 'juniors', '5–7', 'english-lit',
    'Build the foundations of reading through phonics, letter-sound relationships, blending, and early comprehension.',
    'Open storybook with colorful letters jumping out, ABC blocks, magical library scene, flat design, no text',
    ['phonics', 'reading', 'english', 'beginners', 'juniors'],
    'Phonics Foundations',
    ['Letters and Sounds — The Alphabet', 'Vowels and Consonants', 'CVC Words — Cat, Dog, Sun', 'Blending Sounds Together', 'Digraphs — sh, ch, th, ph', 'Reading Simple Sentences'],
    'Phonics Quiz 1',
    'Reading Skills',
    ['Segmenting Words for Spelling', 'High Frequency Words — Sight Words', 'Reading with Expression', 'Understanding What You Read', 'Rhyme and Rhythm', 'Choosing Books You Love'],
    'Phonics Quiz 2',
  ),
  makeHumanitiesCourse(
    'reading-comprehension', 'Reading & Comprehension', 'english-literature', 'elementary', '7–10', 'english-lit',
    'Develop strong reading skills — understanding texts, inferring meaning, identifying themes, and reading for pleasure.',
    'Child reading book with story characters emerging, comprehension questions, flat design, bright colors, no text',
    ['reading', 'comprehension', 'english', 'elementary'],
    'Understanding Texts',
    ['Reading for Meaning — Main Idea', 'Inference — Reading Between the Lines', 'Making Predictions', 'Identifying Characters and Setting', 'Story Structure — Beginning, Middle, End', 'Non-Fiction — Facts and Opinions'],
    'Comprehension Quiz 1',
    'Reading Strategies',
    ['Skimming and Scanning', 'Understanding Vocabulary in Context', 'Summarising What You Read', 'Author\'s Purpose and Viewpoint', 'Comparing Two Texts', 'Book Reviews — Sharing Your Opinion'],
    'Comprehension Quiz 2',
  ),
  makeHumanitiesCourse(
    'creative-writing-juniors', 'Creative Writing for Kids', 'english-literature', 'elementary', '7–10', 'english-lit',
    'Unleash your imagination with stories, characters, settings, and creative writing techniques for young writers.',
    'Child writing in notebook with story characters and magical worlds emerging, colorful flat design, no text',
    ['creative writing', 'stories', 'english', 'imagination', 'elementary'],
    'Story Basics',
    ['Creating Amazing Characters', 'Building Interesting Settings', 'Story Planning — Story Maps', 'Beginnings That Hook Readers', 'Exciting Middles — Conflict and Action', 'Satisfying Endings'],
    'Creative Writing Quiz 1',
    'Writing Techniques',
    ['Show, Don\'t Tell', 'Using Descriptive Language — Adjectives', 'Similes and Metaphors', 'Dialogue — Making Characters Speak', 'Editing and Improving Your Work', 'Publishing Your Story'],
    'Creative Writing Quiz 2',
  ),
  makeHumanitiesCourse(
    'grammar-composition', 'Grammar & Composition', 'english-literature', 'middle', '9–13', 'english-lit',
    'Master English grammar and learn to write clearly and effectively — sentences, punctuation, paragraphs, and style.',
    'Grammar rules chart, sentences, punctuation marks, composition notebook, colorful flat design, no text',
    ['grammar', 'writing', 'english', 'composition', 'middle'],
    'Grammar',
    ['Parts of Speech — Nouns, Verbs, Adjectives, Adverbs', 'Sentences — Simple, Compound, Complex', 'Clauses and Phrases', 'Punctuation — Commas, Semicolons, Colons', 'Tenses — Consistency and Accuracy', 'Agreement — Subject-Verb, Pronoun'],
    'Grammar Quiz',
    'Composition',
    ['Paragraph Structure — PEEL', 'Essay Writing — Introduction and Conclusion', 'Formal vs Informal Writing', 'Persuasive Writing Techniques', 'Report and Non-Fiction Writing', 'Proofreading and Editing'],
    'Composition Quiz',
  ),
  makeHumanitiesCourse(
    'creative-writing-fiction', 'Creative Writing & Fiction', 'english-literature', 'middle', '11–15', 'english-lit',
    'Advanced creative writing — developing voice, genre, plot structure, character development, and literary techniques.',
    'Author at typewriter with fictional worlds and characters emerging, literary symbols, flat design, no text',
    ['creative writing', 'fiction', 'narrative', 'english', 'middle'],
    'Narrative Craft',
    ['Finding Your Voice as a Writer', 'Genre Writing — Mystery, Fantasy, Sci-Fi', 'Narrative Perspective — First, Second, Third Person', 'Plot Structure — Three Acts, Hero\'s Journey', 'Complex Characters — Motivation and Arc', 'Setting as Character'],
    'Fiction Quiz 1',
    'Advanced Techniques',
    ['Foreshadowing and Suspense', 'Symbolism and Imagery', 'Subtext and Implication', 'Pacing and Tension', 'Dialogue that Reveals Character', 'Editing and Polishing Your Fiction'],
    'Fiction Quiz 2',
  ),
  makeHumanitiesCourse(
    'poetry-verse', 'Poetry & Verse', 'english-literature', 'middle', '10–15', 'english-lit',
    'Explore poetry from haiku to sonnets — reading, analysing, and writing your own verse.',
    'Poetry book with colorful verses, quill, rhythm waves, poetic imagery, flat design, no text',
    ['poetry', 'verse', 'english', 'literature', 'middle'],
    'Reading Poetry',
    ['What Makes a Poem?', 'Rhythm and Metre', 'Rhyme Schemes — ABAB, ABBA', 'Poetic Devices — Alliteration, Assonance', 'Imagery and Extended Metaphor', 'Analysing a Poem — Structure and Meaning'],
    'Poetry Quiz 1',
    'Writing Poetry',
    ['Haiku — Nature and Brevity', 'Sonnet — Love and Structure', 'Free Verse — Freedom of Expression', 'Narrative Poetry — Telling Stories', 'Spoken Word and Performance Poetry', 'Anthology Project'],
    'Poetry Quiz 2',
  ),
  makeHumanitiesCourse(
    'literature-classics', 'Literature Classics', 'english-literature', 'secondary', '13–18', 'english-lit',
    'Read and analyse classic and contemporary literature — novels, plays, and poetry in depth.',
    'Classic books with characters, Shakespeare, modern literature, colorful literary flat design, no text',
    ['literature', 'classics', 'shakespeare', 'english', 'secondary', 'gcse'],
    'Classic Prose & Drama',
    ['Introduction to Literary Criticism', 'The Victorian Novel — Dickens, Hardy', 'Shakespeare — A Play in Depth', 'Modern Drama — Miller, Priestley', 'Post-War Fiction — Orwell, Golding', 'Analysing Character and Theme'],
    'Literature Quiz 1',
    'Poetry & Modern Literature',
    ['The Romantics — Keats, Shelley, Wordsworth', 'War Poetry — Owen, Sassoon', 'Post-Colonial Literature', 'Contemporary Fiction', 'Comparing Texts — Themes Across Literature', 'Essay Writing for Literature Exams'],
    'Literature Quiz 2',
  ),
  makeHumanitiesCourse(
    'academic-writing-essay', 'Academic Writing & Essay Skills', 'english-literature', 'advanced', '14–18', 'english-lit',
    'Master the craft of academic writing — argument, evidence, structure, research, and university-level essays.',
    'Essay writing, academic papers, bibliography, argument diagrams, colorful flat design, no text',
    ['academic writing', 'essays', 'english', 'advanced', 'university prep'],
    'Essay Structure',
    ['The Academic Essay — Types and Purposes', 'Thesis Statements and Arguments', 'Paragraph Structure — Topic, Evidence, Analysis', 'Introductions That Engage', 'Conclusions That Resonate', 'Transitions and Cohesion'],
    'Academic Writing Quiz 1',
    'Research & Style',
    ['Research Skills — Finding Sources', 'Evaluating Sources — Credibility', 'Citation and Bibliography — MLA, APA', 'Paraphrasing vs Quoting', 'Academic Vocabulary — Register and Tone', 'Editing for Clarity and Precision'],
    'Academic Writing Quiz 2',
  ),
];

// ── Art & Design ──────────────────────────────────────────────────────────────

export const ART_COURSES: CourseDefinition[] = [
  makeHumanitiesCourse(
    'drawing-sketching-juniors', 'Drawing & Sketching for Beginners', 'art-design', 'juniors', '6–9', 'art-design',
    'Learn to draw with confidence — shapes, lines, observation drawing, characters, and basic illustration techniques.',
    'Artist\'s palette with colorful paint splashes, brushes, canvas, children drawing, flat design, no text',
    ['art', 'drawing', 'sketching', 'beginners', 'juniors'],
    'Drawing Basics',
    ['Drawing Lines — Straight, Curved, Wavy', 'Basic Shapes — Circle, Square, Triangle', 'Drawing from Observation', 'Cartoon Characters — Stick to Detailed', 'Animals — Simple Drawing Techniques', 'Plants and Nature Drawing'],
    'Drawing Quiz 1',
    'Colour & Composition',
    ['Colour — Primary, Secondary, Tertiary', 'Shading with Pencil', 'Perspective — Near and Far', 'Composition — Rule of Thirds', 'Drawing Portraits — Face Proportions', 'My Sketchbook Project'],
    'Drawing Quiz 2',
  ),
  makeHumanitiesCourse(
    'drawing-sketching-intermediate', 'Drawing & Sketching: Next Level', 'art-design', 'middle', '10–14', 'art-design',
    'Develop your drawing skills — figure drawing, still life, landscapes, and expressive techniques.',
    'Detailed sketchbook, figure drawing, still life, landscape, charcoal techniques, flat design, no text',
    ['art', 'drawing', 'figure', 'still life', 'intermediate'],
    'Technical Drawing',
    ['Figure Drawing — Proportions and Gesture', 'Still Life — Light and Shadow', 'Landscape Drawing — Horizon and Depth', 'Technical Pen and Ink', 'Contour Drawing', 'Blind Contour and Gesture Exercises'],
    'Drawing Intermediate Quiz 1',
    'Style & Expression',
    ['Developing Your Style', 'Illustration — Editorial and Book', 'Fashion and Character Design', 'Architectural Drawing Basics', 'Mixed Media Drawing', 'Portfolio Building'],
    'Drawing Intermediate Quiz 2',
  ),
  makeHumanitiesCourse(
    'drawing-sketching-advanced', 'Advanced Drawing & Illustration', 'art-design', 'secondary', '14–18', 'art-design',
    'Master advanced drawing techniques — expressive mark-making, concept art, illustration, and professional portfolio.',
    'Professional illustration setup, concept art, advanced sketching, portfolio, flat design, no text',
    ['art', 'drawing', 'illustration', 'advanced', 'portfolio'],
    'Advanced Techniques',
    ['Advanced Anatomy for Artists', 'Perspective — 1, 2, 3 Point', 'Value and Tonal Studies', 'Texture and Surface Rendering', 'Concept Art — Character Design', 'Environment and World Building'],
    'Advanced Drawing Quiz 1',
    'Professional Practice',
    ['Illustration Styles — Comparison', 'Digital Drawing Fundamentals', 'Creating a Series of Illustrations', 'Artist Statement and Process', 'Portfolio Development', 'Career Paths in Illustration'],
    'Advanced Drawing Quiz 2',
  ),
  makeHumanitiesCourse(
    'painting-watercolors', 'Painting & Watercolors', 'art-design', 'elementary', '8–14', 'art-design',
    'Explore the joy of painting — watercolour, acrylic, colour theory, and building confidence as an artist.',
    'Watercolor painting with vibrant washes, paint palette, brushes, colorful artwork, flat design, no text',
    ['art', 'painting', 'watercolour', 'colour theory', 'elementary'],
    'Watercolour Basics',
    ['Materials — Brushes, Paper, Paints', 'Wet on Wet vs Wet on Dry', 'Colour Mixing — Warm and Cool', 'Washes — Flat, Graded, Variegated', 'Painting Landscapes', 'Painting Flowers'],
    'Watercolour Quiz 1',
    'Acrylic & Expression',
    ['Introduction to Acrylic Paint', 'Layering and Texture', 'Painting Portraits in Acrylics', 'Abstract Painting — Expressing Emotions', 'Mixed Media — Collage and Paint', 'Creating a Series'],
    'Painting Quiz 2',
  ),
  makeHumanitiesCourse(
    'digital-art-illustration', 'Digital Art & Illustration', 'art-design', 'middle', '10–18', 'art-design',
    'Create stunning digital art using design tools — illustration, photo editing, typography, and UI design basics.',
    'Tablet with digital illustrations, design software icons, colorful digital artwork, flat design, no text',
    ['art', 'digital art', 'illustration', 'design software', 'middle'],
    'Digital Foundations',
    ['Introduction to Digital Art Tools', 'Layers — The Foundation of Digital Art', 'Digital Brushes and Textures', 'Digital Colouring Techniques', 'Character Design Digitally', 'Backgrounds and Environments'],
    'Digital Art Quiz 1',
    'Advanced Digital Creation',
    ['Photo Manipulation and Editing', 'Typography and Lettering', 'Vector Art — Clean Line Work', 'Animation Basics — Frame by Frame', 'Creating a Digital Zine or Comic', 'Building a Digital Portfolio'],
    'Digital Art Quiz 2',
  ),
  makeHumanitiesCourse(
    'photography', 'Photography — From Selfies to Stories', 'art-design', 'secondary', '11–18', 'art-design',
    'Learn the art and craft of photography — composition, light, exposure, editing, and storytelling through images.',
    'Camera with colorful photographs around it, composition grid, light settings, flat design, no text',
    ['photography', 'composition', 'light', 'editing', 'secondary'],
    'Photography Fundamentals',
    ['Introduction to Photography — Camera Types', 'The Exposure Triangle — Aperture, Shutter, ISO', 'Composition — Rule of Thirds, Leading Lines', 'Lighting — Natural and Artificial', 'Genres — Portrait, Landscape, Street', 'Storytelling with Images'],
    'Photography Quiz 1',
    'Editing & Expression',
    ['Photo Editing — Basic Corrections', 'Colour Grading and Mood', 'Black and White Photography', 'Documentary Photography', 'Photo Essays — Creating a Series', 'Ethical Photography'],
    'Photography Quiz 2',
  ),
  makeHumanitiesCourse(
    'graphic-design', 'Graphic Design Fundamentals', 'art-design', 'secondary', '12–18', 'art-design',
    'Learn design principles — typography, colour, layout, branding, and create professional visual communications.',
    'Graphic design elements — typography, color palette, logo design, layout grids, flat design, no text',
    ['graphic design', 'typography', 'branding', 'layout', 'secondary'],
    'Design Principles',
    ['Elements of Design — Line, Shape, Colour', 'Principles of Design — Balance, Contrast', 'Typography — Fonts and Hierarchy', 'Colour Theory for Designers', 'Layout and Composition', 'Branding — Logos and Visual Identity'],
    'Graphic Design Quiz 1',
    'Applied Design',
    ['Print Design — Posters and Flyers', 'Social Media Graphics', 'Infographic Design', 'Packaging Design Basics', 'User Interface Design Basics', 'Design Portfolio Project'],
    'Graphic Design Quiz 2',
  ),
  makeHumanitiesCourse(
    'video-production-editing', 'Video Production & Editing', 'art-design', 'secondary', '12–18', 'art-design',
    'Create compelling videos — planning, filming, editing, sound design, and storytelling through film.',
    'Video camera, film editing timeline, storyboard, colorful production icons, flat design, no text',
    ['video production', 'film', 'editing', 'storytelling', 'secondary'],
    'Production',
    ['Pre-Production — Idea and Script', 'Storyboarding Your Video', 'Camera Techniques — Shots and Angles', 'Lighting for Video', 'Sound — Recording and Microphones', 'Filming Your First Project'],
    'Video Production Quiz 1',
    'Post-Production',
    ['Introduction to Video Editing Software', 'Cutting and Sequencing', 'Colour Grading', 'Sound Editing and Music', 'Titles, Graphics, and Effects', 'Publishing and Sharing Your Film'],
    'Video Production Quiz 2',
  ),
];

// ── Music ─────────────────────────────────────────────────────────────────────

export const MUSIC_COURSES: CourseDefinition[] = [
  makeHumanitiesCourse(
    'music-appreciation', 'Music Appreciation', 'music', 'juniors', '6–10', 'music',
    'Discover the wonderful world of music — instruments, genres, rhythm, melody, and the joy of listening.',
    'Musical notes floating from piano, guitar, violin, colorful sound waves, flat design, bright colors, no text',
    ['music', 'appreciation', 'instruments', 'listening', 'juniors'],
    'Elements of Music',
    ['What is Music?', 'The Orchestra — Instrument Families', 'Rhythm — Beat and Metre', 'Melody — High and Low Sounds', 'Dynamics — Loud and Soft', 'Tempo — Fast and Slow'],
    'Music Appreciation Quiz 1',
    'Genres & World Music',
    ['Classical Music — Famous Composers', 'Pop and Rock Music', 'Jazz and Blues', 'World Music — Samba, Bollywood', 'Folk and Traditional Music', 'How Music Makes Us Feel'],
    'Music Appreciation Quiz 2',
  ),
  makeHumanitiesCourse(
    'music-theory-fundamentals', 'Music Theory Fundamentals', 'music', 'elementary', '8–14', 'music',
    'Learn to read and write music — notes, rhythms, scales, chords, and the building blocks of musical understanding.',
    'Music staff with notes, treble clef, piano keys, colorful theory charts, flat design, no text',
    ['music theory', 'notes', 'scales', 'chords', 'elementary'],
    'Notation & Rhythm',
    ['Reading Music — Treble Clef', 'Note Values — Crotchet, Quaver, Minim', 'Time Signatures — 4/4, 3/4', 'The Stave and Ledger Lines', 'Rests and Silence', 'Sight-Reading Simple Melodies'],
    'Music Theory Quiz 1',
    'Scales & Chords',
    ['The Major Scale', 'The Minor Scale', 'Intervals — Steps and Leaps', 'Chords — Triads', 'Chord Progressions — I IV V', 'Key Signatures and Key Changes'],
    'Music Theory Quiz 2',
  ),
  makeHumanitiesCourse(
    'piano-keyboard-beginners', 'Piano & Keyboard for Beginners', 'music', 'juniors', '6–12', 'music',
    'Start your piano journey — hand position, notes, simple melodies, and playing your first songs.',
    'Piano keyboard with colorful note labels, hands playing, sheet music, flat design, no text',
    ['piano', 'keyboard', 'music', 'beginners', 'instrument'],
    'Getting Started',
    ['Piano Layout — Black and White Keys', 'Sitting Posture and Hand Position', 'Reading Treble Clef — Right Hand', 'Reading Bass Clef — Left Hand', 'Playing C Major Scale', 'Your First Song — Hot Cross Buns'],
    'Piano Beginners Quiz 1',
    'Developing Skills',
    ['Playing with Both Hands Together', 'Simple Chord Accompaniment', 'Dynamics — Playing Loud and Soft', 'Legato and Staccato', 'Playing by Ear', 'Mini Recital Piece'],
    'Piano Beginners Quiz 2',
  ),
  makeHumanitiesCourse(
    'piano-keyboard-intermediate', 'Piano & Keyboard: Intermediate', 'music', 'middle', '10–18', 'music',
    'Develop piano technique — scales, arpeggios, chord voicings, sight-reading, and playing expressive pieces.',
    'Piano with sheet music, advanced notation, expressive playing, concert hall, flat design, no text',
    ['piano', 'keyboard', 'intermediate', 'technique', 'music'],
    'Technique',
    ['Major and Minor Scales — Two Octaves', 'Arpeggios — Broken Chords', 'Coordination — Hands Independent', 'Chord Inversions', 'Sight-Reading Intermediate Pieces', 'Technical Exercises — Hanon, Czerny'],
    'Piano Intermediate Quiz 1',
    'Repertoire & Expression',
    ['Classical Piece Study', 'Pop and Contemporary Styles', 'Improvisation Basics', 'Music Theory Applied to Piano', 'Pedalling Techniques', 'Performance Preparation'],
    'Piano Intermediate Quiz 2',
  ),
  makeHumanitiesCourse(
    'guitar-beginners', 'Guitar for Beginners', 'music', 'elementary', '8–14', 'music',
    'Learn guitar from scratch — chord shapes, strumming, reading tab, and playing your favourite songs.',
    'Acoustic guitar with chord diagrams, picking hand, colorful music notes, flat design, no text',
    ['guitar', 'music', 'beginners', 'chords', 'strumming'],
    'First Steps',
    ['Parts of the Guitar', 'Tuning Your Guitar', 'Finger Placement and Basic Chords — Em, Am, D', 'G, C, E Chords', 'Strumming Patterns', 'Your First Song'],
    'Guitar Beginners Quiz 1',
    'Building Skills',
    ['Reading Guitar Tablature (Tab)', 'Barre Chords Introduction', 'Fingerpicking Basics', 'Playing in Different Keys', 'Songs in Multiple Styles', 'Practising Effectively'],
    'Guitar Beginners Quiz 2',
  ),
  makeHumanitiesCourse(
    'guitar-intermediate', 'Guitar Intermediate & Advanced', 'music', 'secondary', '12–18', 'music',
    'Take your guitar playing to the next level — scales, solos, music theory, styles, and performance.',
    'Electric guitar with amp, scales diagram, rock and jazz guitar styles, colorful flat design, no text',
    ['guitar', 'intermediate', 'scales', 'solos', 'music theory', 'secondary'],
    'Technique & Theory',
    ['The Pentatonic Scale', 'The Major and Minor Scales on Guitar', 'Modes Introduction', 'Lead Guitar — Bending, Vibrato, Hammer-Ons', 'Music Theory for Guitarists', 'Chord Progressions and Songwriting'],
    'Guitar Intermediate Quiz 1',
    'Styles & Improvisation',
    ['Rock and Blues Guitar', 'Jazz Chord Voicings', 'Classical Guitar Technique', 'Acoustic Fingerstyle', 'Improvisation Over Chord Changes', 'Recording and Home Studio Basics'],
    'Guitar Intermediate Quiz 2',
  ),
  makeHumanitiesCourse(
    'music-production-beat-making', 'Music Production & Beat Making', 'music', 'secondary', '12–18', 'music',
    'Create your own music — beats, melodies, mixing, and producing tracks using Digital Audio Workstations.',
    'Music production studio with DAW, MIDI keyboard, beats, headphones, colorful flat design, no text',
    ['music production', 'beats', 'daw', 'mixing', 'secondary'],
    'Production Basics',
    ['Introduction to DAWs — GarageBand, FL Studio', 'Drum Programming — 808 and Beats', 'Melody Writing — Piano Roll', 'Sampling and Loops', 'Bass Lines and Chords', 'Song Structure — Intro, Verse, Chorus'],
    'Music Production Quiz 1',
    'Mixing & Release',
    ['Mixing — Volume and Panning', 'EQ — Sculpting Your Sound', 'Compression Basics', 'Reverb and Effects', 'Mastering for Streaming', 'Releasing Your Music Online'],
    'Music Production Quiz 2',
  ),
];

// ── Drama & Performance ───────────────────────────────────────────────────────

export const DRAMA_COURSES: CourseDefinition[] = [
  makeHumanitiesCourse(
    'drama-storytelling', 'Drama & Storytelling', 'drama-performance', 'juniors', '6–12', 'drama',
    'Build confidence through drama — role play, storytelling, mime, improvisation, and sharing your voice.',
    'Stage spotlight on theatrical masks, colorful curtains, children performing, flat design, no text',
    ['drama', 'storytelling', 'performance', 'confidence', 'juniors'],
    'Drama Basics',
    ['What is Drama?', 'Using Your Voice — Pitch, Volume, Pace', 'Using Your Body — Movement and Gesture', 'Mime — Telling Stories Without Words', 'Improvisation — Making It Up!', 'Storytelling Techniques'],
    'Drama Quiz 1',
    'Performance',
    ['Role Play — Becoming a Character', 'Tableau — Creating Frozen Images', 'Hot Seating — Questioning Characters', 'Creating a Short Scene', 'Working Together — Ensemble Performance', 'Mini Performance Showcase'],
    'Drama Quiz 2',
  ),
  makeHumanitiesCourse(
    'theatre-arts', 'Theatre Arts', 'drama-performance', 'middle', '10–16', 'drama',
    'Explore theatre from all angles — acting, directing, staging, script analysis, and theatrical history.',
    'Theatre stage with set design, spotlight, script, director\'s chair, colorful flat design, no text',
    ['drama', 'theatre', 'acting', 'directing', 'middle'],
    'Acting & Analysis',
    ['Stanislavski\'s Method — Motivation and Objective', 'Brechtian Theatre — Epic Acting', 'Script Analysis — Character and Subtext', 'Voice and Movement Exercises', 'Monologue Performance', 'Duologue and Ensemble Work'],
    'Theatre Arts Quiz 1',
    'Production Elements',
    ['Staging — Blocking and Stage Areas', 'Set Design and Staging', 'Lighting — Effects and Mood', 'Costume and Character', 'Stage Management Basics', 'Theatre Review Writing'],
    'Theatre Arts Quiz 2',
  ),
  makeHumanitiesCourse(
    'public-speaking-debate', 'Public Speaking & Debate', 'drama-performance', 'middle', '11–18', 'drama',
    'Develop your voice and argumentation skills — speeches, debates, presentations, and confident communication.',
    'Speaker at podium, debate competition, presentation slides, confident microphone, flat design, no text',
    ['public speaking', 'debate', 'communication', 'argument', 'middle'],
    'Public Speaking',
    ['Overcoming Nerves', 'Structuring a Speech', 'Vocal Techniques — Pace, Pause, Emphasis', 'Body Language and Presence', 'Persuasive Speaking', 'Impromptu Speaking'],
    'Public Speaking Quiz 1',
    'Debate',
    ['Debate Formats — Formal Debate', 'Research and Building Arguments', 'Constructing Rebuttal', 'Logical Fallacies to Avoid', 'The Ethics of Argument', 'Mock Debate Competition'],
    'Debate Quiz 2',
  ),
  makeHumanitiesCourse(
    'film-studies-cinema', 'Film Studies & Cinema', 'drama-performance', 'secondary', '13–18', 'drama',
    'Analyse film as an art form — cinematography, narrative, genre, auteur theory, and the history of cinema.',
    'Film reel, camera angle diagrams, movie poster art, director\'s clapperboard, colorful flat design, no text',
    ['film studies', 'cinema', 'analysis', 'media', 'secondary'],
    'Film Language',
    ['Introduction to Film Studies', 'Cinematography — Shot Types and Angles', 'Editing — Montage and Continuity', 'Sound Design — Diegetic and Non-Diegetic', 'Genre — Conventions and Subversion', 'Narrative Structure in Film'],
    'Film Studies Quiz 1',
    'Film in Context',
    ['Hollywood and World Cinema', 'The Auteur Theory — Directors as Authors', 'Documentary Film', 'Representation — Gender, Race, Class', 'Film and Society — Propaganda and Ideology', 'Contemporary Cinema — Streaming and Future of Film'],
    'Film Studies Quiz 2',
  ),
];

// ── Combined Export ───────────────────────────────────────────────────────────

export const HUMANITIES_COURSES: CourseDefinition[] = [
  ...ENGLISH_LIT_COURSES,
  ...ART_COURSES,
  ...MUSIC_COURSES,
  ...DRAMA_COURSES,
];
