import type { CourseDefinition } from '../types.js';

// ── Helper ────────────────────────────────────────────────────────────────────

function makeSkillsCourse(
  slug: string,
  title: string,
  categorySlug: string,
  ageGroup: CourseDefinition['ageGroup'],
  description: string,
  imagePrompt: string,
  tags: string[],
  section1Title: string,
  lessons1: string[],
  quiz1Title: string,
  section2Title: string,
  lessons2: string[],
  quiz2Title: string,
): CourseDefinition {
  const makeLesson = (t: string, idx: number) => ({
    title: t, slug: `${slug}-lesson-${idx + 1}`, order: idx + 1,
  });
  const makeQ = (q: string) => ({ question: q, type: 'multiple_choice' as const });
  const defaultQuestions = [
    `What is the main skill or concept covered in this section of ${title}?`,
    `Which of the following best describes a key idea from this lesson?`,
    `How would you apply this skill in real life?`,
    `What is the correct approach to the topic just covered?`,
    `Which example best demonstrates the concept you just learned?`,
    `What would be the result of applying this skill incorrectly?`,
    `Which statement is TRUE about this topic?`,
    `How does this skill connect to your daily life and future goals?`,
  ];
  return {
    title, slug, description, excerpt: description.slice(0, 120) + '...',
    categorySlug, ageGroup, type: 'self-paced', hasCertification: true,
    imagePrompt, tags,
    sections: [
      {
        title: section1Title, order: 1,
        lessons: lessons1.map((t, i) => makeLesson(t, i)),
        quizzes: [{
          title: quiz1Title, slug: `${slug}-quiz-1`,
          questions: defaultQuestions.map(makeQ),
        }],
      },
      {
        title: section2Title, order: 2,
        lessons: lessons2.map((t, i) => makeLesson(t, i + lessons1.length)),
        quizzes: [{
          title: quiz2Title, slug: `${slug}-quiz-2`,
          questions: defaultQuestions.map(makeQ),
        }],
      },
    ],
  };
}

// ── Life Skills (8 courses) ───────────────────────────────────────────────────

export const LIFE_SKILLS_COURSES: CourseDefinition[] = [
  makeSkillsCourse(
    'mindfulness-emotional-intelligence',
    'Mindfulness & Emotional Intelligence',
    'life-skills',
    'juniors',
    'Learn to understand your emotions, practice mindfulness, and build healthy relationships with others through age-appropriate exercises.',
    'colorful cartoon children practicing mindfulness meditation with glowing hearts and calm peaceful expressions, flat design illustration',
    ['mindfulness', 'emotional intelligence', 'meditation', 'self-awareness', 'empathy'],
    'Understanding Emotions',
    ['What Are Emotions?', 'Identifying Your Feelings', 'Why Emotions Matter', 'The Emotion Wheel', 'Emotions and the Body', 'When Emotions Feel Too Big'],
    'Emotions Check-In Quiz',
    'Mindfulness in Practice',
    ['What Is Mindfulness?', 'Breathing Exercises for Kids', 'Body Scan for Beginners', 'Mindful Listening', 'Gratitude Practice', 'Building Empathy for Others'],
    'Mindfulness Skills Quiz',
  ),
  makeSkillsCourse(
    'study-skills-learning',
    'Study Skills & Learning How to Learn',
    'life-skills',
    'elementary',
    'Master the science of learning: memory techniques, note-taking strategies, time management, and how to study smarter for any subject.',
    'bright organized study desk with notes, flashcards, colorful pens and books arranged neatly, flat design educational illustration',
    ['study skills', 'learning techniques', 'memory', 'note-taking', 'time management'],
    'How Your Brain Learns',
    ['The Science of Memory', 'Active vs Passive Learning', 'Spaced Repetition', 'The Forgetting Curve', 'Growth Mindset Basics', 'Setting Learning Goals'],
    'Learning Science Quiz',
    'Study Strategies That Work',
    ['Cornell Note-Taking Method', 'Mind Maps and Visual Notes', 'Pomodoro Technique', 'Practice Testing', 'Eliminating Distractions', 'Creating Your Study Schedule'],
    'Study Strategies Quiz',
  ),
  makeSkillsCourse(
    'research-critical-thinking',
    'Research & Critical Thinking',
    'life-skills',
    'middle',
    'Develop powerful critical thinking skills: evaluate sources, spot logical fallacies, construct arguments, and make evidence-based decisions.',
    'magnifying glass over colorful documents with checkmarks and question marks, analytical thinking illustration for students, flat design',
    ['critical thinking', 'research skills', 'logic', 'argumentation', 'media literacy'],
    'Foundations of Critical Thinking',
    ['What Is Critical Thinking?', 'Asking Good Questions', 'Evaluating Sources', 'Fact vs Opinion', 'Logical Fallacies Explained', 'Confirmation Bias'],
    'Critical Thinking Foundations Quiz',
    'Research and Argumentation',
    ['How to Research Effectively', 'Building Strong Arguments', 'Citing Sources Correctly', 'Analyzing Data and Statistics', 'Debate Skills', 'Writing Evidence-Based Conclusions'],
    'Research Skills Quiz',
  ),
  makeSkillsCourse(
    'leadership-teamwork',
    'Leadership & Teamwork',
    'life-skills',
    'middle',
    'Discover leadership styles, team dynamics, conflict resolution, and how to collaborate effectively to achieve shared goals.',
    'diverse group of young students working together as a team with a leader guiding them, colorful teamwork illustration, flat design',
    ['leadership', 'teamwork', 'collaboration', 'communication', 'conflict resolution'],
    'Leadership Fundamentals',
    ['What Makes a Great Leader?', 'Leadership Styles Compared', 'Self-Leadership First', 'Setting a Vision', 'Motivating Others', 'Ethical Leadership'],
    'Leadership Foundations Quiz',
    'Teamwork and Collaboration',
    ['Building Effective Teams', 'Roles Within a Team', 'Communication in Teams', 'Handling Conflict Constructively', 'Decision Making as a Group', 'Leading a Project'],
    'Teamwork Skills Quiz',
  ),
  makeSkillsCourse(
    'communication-skills',
    'Communication Skills',
    'life-skills',
    'elementary',
    'Build confident communication skills: verbal, non-verbal, written, and digital communication for school, friendships, and beyond.',
    'children talking, writing and presenting with speech bubbles and communication icons, bright colorful illustration, flat design',
    ['communication', 'public speaking', 'writing', 'listening', 'body language'],
    'The Art of Communication',
    ['What Is Communication?', 'Verbal vs Non-Verbal', 'Active Listening Skills', 'Body Language Basics', 'Tone and Emotion', 'Barriers to Good Communication'],
    'Communication Fundamentals Quiz',
    'Speaking and Writing with Impact',
    ['How to Speak Confidently', 'Giving a Short Presentation', 'Writing Clear Messages', 'Email Etiquette for Students', 'Digital Communication Rules', 'Giving and Receiving Feedback'],
    'Communication in Practice Quiz',
  ),
  makeSkillsCourse(
    'career-exploration',
    'Career Exploration',
    'life-skills',
    'secondary',
    'Explore careers, understand the world of work, identify your strengths and interests, and create a roadmap for your future.',
    'colorful career options spread in a circle around a student thinking, diverse professions illustrated, flat design',
    ['career', 'future planning', 'strengths', 'interests', 'work skills'],
    'Knowing Yourself',
    ['Your Strengths and Interests', 'Personality and Career Fit', 'Values in the Workplace', 'Skills Inventory', 'Setting Career Goals', 'The World of Work Today'],
    'Self-Discovery Quiz',
    'Exploring Career Paths',
    ['Careers in Technology', 'Careers in Creative Fields', 'Careers in Healthcare and Science', 'Careers in Business', 'Entrepreneurship as a Career', 'Building Your Career Plan'],
    'Career Exploration Quiz',
  ),
  makeSkillsCourse(
    'university-college-prep',
    'University & College Preparation',
    'life-skills',
    'advanced',
    'Everything you need to know to apply successfully to university: applications, personal statements, interviews, scholarships, and what to expect.',
    'student with graduation cap surrounded by university buildings and application documents, achievement illustration, flat design',
    ['university', 'college application', 'personal statement', 'scholarships', 'campus life'],
    'Getting Ready for University',
    ['Understanding University Systems', 'Choosing the Right Course', 'Entry Requirements Explained', 'Building a Strong Application', 'Writing Your Personal Statement', 'Getting Great References'],
    'University Preparation Quiz',
    'Applications, Finance and Life at Uni',
    ['How to Apply Step by Step', 'Student Finance and Scholarships', 'Preparing for Interviews', 'Accommodation and Campus Life', 'Transitioning to Independence', 'Making the Most of University'],
    'University Life Quiz',
  ),
  makeSkillsCourse(
    'interview-professional-skills',
    'Interview & Professional Skills',
    'life-skills',
    'advanced',
    'Master job applications, CV writing, interview techniques, workplace communication, and professional etiquette for career success.',
    'student in professional attire shaking hands in an interview, modern office setting illustration, flat design',
    ['interview skills', 'CV writing', 'professional skills', 'workplace', 'career'],
    'Job Applications and CVs',
    ['What Employers Look For', 'Writing a Winning CV', 'Cover Letter Essentials', 'Online Profiles and LinkedIn', 'Understanding Job Descriptions', 'Tailoring Every Application'],
    'Job Application Skills Quiz',
    'Interview and Workplace Success',
    ['Types of Job Interviews', 'Common Interview Questions', 'The STAR Answer Technique', 'Dressing and Presenting Yourself', 'Workplace Communication', 'Professional Ethics and Conduct'],
    'Interview & Professional Skills Quiz',
  ),
];

// ── Physical Education & Health (6 courses) ──────────────────────────────────

export const PE_HEALTH_COURSES: CourseDefinition[] = [
  makeSkillsCourse(
    'active-play-movement',
    'Active Play & Movement',
    'pe-health',
    'juniors',
    'Fun movement activities, games, and exercises that help young children develop coordination, balance, and a love of being active.',
    'happy children running, jumping and playing sports outside on a sunny day, colorful energetic illustration, flat design',
    ['physical activity', 'movement', 'games', 'coordination', 'health'],
    'Moving Your Body',
    ['Why Movement Matters', 'Balance and Coordination', 'Running and Jumping Safely', 'Throwing and Catching', 'Dance and Rhythm', 'Games That Keep You Moving'],
    'Active Movement Quiz',
    'Fun and Fitness',
    ['Team Sports for Beginners', 'Gymnastics Basics', 'Swimming Safety', 'Yoga for Kids', 'Outdoor Adventure Games', 'Building a Daily Activity Habit'],
    'Physical Play Quiz',
  ),
  makeSkillsCourse(
    'physical-fitness-exercise',
    'Physical Fitness & Exercise',
    'pe-health',
    'middle',
    'Learn about fitness components, design your own workout routine, and understand how exercise benefits your body and mind.',
    'teenage students exercising in a bright gym with various fitness equipment, flat design sports illustration',
    ['fitness', 'exercise', 'workout', 'strength', 'cardio'],
    'Understanding Fitness',
    ['The Components of Fitness', 'How the Body Responds to Exercise', 'Cardio Training Basics', 'Strength Training for Teens', 'Flexibility and Stretching', 'Fitness Testing and Goals'],
    'Fitness Fundamentals Quiz',
    'Building Your Fitness Routine',
    ['Designing a Workout Plan', 'Warming Up and Cooling Down', 'Rest and Recovery', 'Avoiding Injury', 'Tracking Your Progress', 'Staying Motivated'],
    'Exercise Science Quiz',
  ),
  makeSkillsCourse(
    'sports-science',
    'Sports Science',
    'pe-health',
    'secondary',
    'Explore the science behind athletic performance: biomechanics, physiology, nutrition for athletes, sports psychology, and injury prevention.',
    'athlete in motion with body mechanics overlay diagrams, science of sport illustration, flat design',
    ['sports science', 'biomechanics', 'physiology', 'athletic performance', 'sports psychology'],
    'The Human Body in Sport',
    ['How Muscles Work', 'Energy Systems in Sport', 'Biomechanics of Movement', 'Cardiovascular Performance', 'Thermoregulation and Hydration', 'Performance Testing'],
    'Sports Physiology Quiz',
    'Psychology and Performance',
    ['Sports Psychology Basics', 'Goal Setting for Athletes', 'Arousal and Performance', 'Visualization Techniques', 'Nutrition for Athletes', 'Injury Prevention and Rehabilitation'],
    'Sports Science Application Quiz',
  ),
  makeSkillsCourse(
    'nutrition-healthy-living',
    'Nutrition & Healthy Living',
    'pe-health',
    'elementary',
    'Understand food groups, balanced diets, reading food labels, and how your daily habits shape your health now and in the future.',
    'colorful fruits, vegetables and healthy foods arranged in a rainbow pattern, nutrition for kids illustration, flat design',
    ['nutrition', 'healthy eating', 'food groups', 'diet', 'wellness'],
    'Food and Your Body',
    ['Why We Need Food', 'The Main Nutrient Groups', 'Carbohydrates and Energy', 'Proteins and Growth', 'Fats — Good and Bad', 'Vitamins and Minerals'],
    'Nutrition Basics Quiz',
    'Eating Well Every Day',
    ['Reading Food Labels', 'The Balanced Plate Method', 'Hydration and Water', 'Sugar and Processed Food', 'Meal Planning for Teens', 'Making Healthier Choices'],
    'Healthy Eating Quiz',
  ),
  makeSkillsCourse(
    'mental-health-wellbeing',
    'Mental Health & Wellbeing',
    'pe-health',
    'middle',
    'Understand mental health, manage stress and anxiety, build resilience, and know when and how to ask for help.',
    'calm serene illustration of a teenager sitting under a tree with thought bubbles showing positive coping strategies, flat design',
    ['mental health', 'wellbeing', 'stress management', 'resilience', 'anxiety'],
    'Understanding Mental Health',
    ['What Is Mental Health?', 'Common Mental Health Challenges', 'Stress and How It Works', 'Anxiety Explained', 'Depression Awareness', 'Breaking the Stigma'],
    'Mental Health Awareness Quiz',
    'Building Resilience and Getting Help',
    ['Coping Strategies That Work', 'Resilience and Bounce-Back', 'Sleep and Mental Health', 'Social Media and Wellbeing', 'When to Ask for Help', 'Supporting Friends with Struggles'],
    'Wellbeing Skills Quiz',
  ),
  makeSkillsCourse(
    'first-aid-safety',
    'First Aid & Safety',
    'pe-health',
    'middle',
    'Learn essential first aid skills, safety procedures, and how to respond calmly and effectively in emergencies.',
    'first aid kit with bandages, emergency equipment and safety symbols, calm professional illustration, flat design',
    ['first aid', 'safety', 'emergency response', 'CPR', 'health'],
    'Safety and Prevention',
    ['Home and School Safety', 'Road Safety Rules', 'Online Safety', 'Fire Safety Basics', 'Water Safety', 'Preventing Common Accidents'],
    'Safety Awareness Quiz',
    'First Aid Skills',
    ['What Is First Aid?', 'Calling Emergency Services', 'Basic CPR for Beginners', 'Treating Cuts and Burns', 'Choking Response', 'First Aid for Sports Injuries'],
    'First Aid Skills Quiz',
  ),
];

// ── World Cultures & Religious Studies (5 courses) ───────────────────────────

export const WORLD_CULTURES_COURSES: CourseDefinition[] = [
  makeSkillsCourse(
    'festivals-around-world',
    'Festivals Around the World',
    'world-cultures',
    'juniors',
    'Travel the world through celebrations! Discover the stories, food, music, and traditions behind the most colourful festivals from every continent.',
    'vibrant colorful world map with festival celebration icons from different cultures, illustrated globes and fireworks, flat design',
    ['festivals', 'cultures', 'traditions', 'celebrations', 'world cultures'],
    'Celebrating Around the Globe',
    ['What Are Festivals?', 'New Year Around the World', 'Diwali — Festival of Lights', 'Chinese New Year', 'Christmas Traditions Worldwide', 'Eid Celebrations'],
    'World Festivals Quiz',
    'More Festivals to Explore',
    ['Hanukkah and Jewish Festivals', 'Carnival in Brazil', 'Halloween Origins', 'Día de los Muertos', 'Holi — Festival of Colours', 'Indigenous Festivals'],
    'Cultural Celebrations Quiz',
  ),
  makeSkillsCourse(
    'world-religions',
    'World Religions',
    'world-cultures',
    'middle',
    'An objective and respectful exploration of the world\'s major religions — their beliefs, practices, sacred texts, and role in shaping human civilization.',
    'world religions symbols arranged in harmony — cross, crescent, Star of David, Om, Dharma wheel, illustrated respectfully, flat design',
    ['world religions', 'Christianity', 'Islam', 'Hinduism', 'Buddhism', 'Judaism'],
    'The Major World Religions',
    ['What Is Religion?', 'Christianity Explored', 'Islam and Its Pillars', 'Hinduism — Beliefs and Practices', 'Buddhism and the Eightfold Path', 'Judaism — History and Belief'],
    'World Religions Quiz',
    'More Faiths and Perspectives',
    ['Sikhism', 'Indigenous and Folk Religions', 'Secular Humanism', 'Religion and Science', 'Religion in History', 'Religious Tolerance and Dialogue'],
    'Faith and Culture Quiz',
  ),
  makeSkillsCourse(
    'cultural-diversity-inclusion',
    'Cultural Diversity & Inclusion',
    'world-cultures',
    'middle',
    'Explore why diversity makes communities stronger, understand bias and stereotyping, and develop skills to be an inclusive global citizen.',
    'diverse group of children from different cultures holding hands in a circle representing unity and inclusion, flat design illustration',
    ['diversity', 'inclusion', 'multicultural', 'equality', 'global citizenship'],
    'Understanding Diversity',
    ['What Is Culture?', 'The World\'s Languages', 'Race, Ethnicity and Identity', 'Stereotypes and Bias', 'The History of Prejudice', 'Celebrating Difference'],
    'Diversity Awareness Quiz',
    'Being an Inclusive Person',
    ['What Is Inclusion?', 'Privilege and Perspective', 'Standing Up Against Discrimination', 'Being an Ally', 'Inclusive Language', 'Creating Inclusive Communities'],
    'Inclusion in Action Quiz',
  ),
  makeSkillsCourse(
    'mythology-folklore',
    'Mythology & Folklore',
    'world-cultures',
    'elementary',
    'Explore the fascinating myths, legends, and folk tales from ancient Greece, Norse mythology, Egyptian stories, and cultures around the world.',
    'epic mythological scene with greek gods, norse warriors and world folklore creatures in a magical landscape, illustration, flat design',
    ['mythology', 'folklore', 'legends', 'Greek mythology', 'Norse mythology'],
    'Ancient Myths and Stories',
    ['What Is Mythology?', 'Greek Gods and Heroes', 'The Odyssey', 'Norse Gods — Odin, Thor, and Loki', 'Egyptian Gods and Pharaohs', 'Roman Mythology'],
    'Mythology Quiz',
    'Folklore from Around the World',
    ['Celtic Legends and Fairies', 'African Folklore and Anansi', 'Chinese Dragon Myths', 'Japanese Folklore', 'Indigenous Dreamtime Stories', 'Why Myths Matter Today'],
    'World Folklore Quiz',
  ),
  makeSkillsCourse(
    'global-citizenship',
    'Global Citizenship',
    'world-cultures',
    'secondary',
    'What does it mean to be a global citizen? Explore international relations, global challenges, human rights, and your role in the world.',
    'globe surrounded by diverse people connected by lines of light representing global community and cooperation, flat design illustration',
    ['global citizenship', 'international relations', 'human rights', 'sustainability', 'global issues'],
    'Being a Global Citizen',
    ['What Is Global Citizenship?', 'The United Nations', 'Human Rights Framework', 'Global Economic Inequality', 'Migration and Refugees', 'International Conflict and Peace'],
    'Global Citizenship Foundations Quiz',
    'Acting Globally',
    ['Climate Change as a Global Issue', 'Sustainable Development Goals', 'Social Movements and Change', 'Digital Global Citizenship', 'How Young People Change the World', 'Your Global Action Plan'],
    'Global Action Quiz',
  ),
];

// ── Environmental & Sustainability Studies (4 courses) ────────────────────────

export const ENVIRONMENT_COURSES: CourseDefinition[] = [
  makeSkillsCourse(
    'nature-conservation',
    'Nature & Conservation',
    'environment',
    'juniors',
    'Fall in love with nature! Explore ecosystems, amazing animals, plants, and why protecting the natural world is so important for our future.',
    'beautiful natural ecosystem with animals, plants and a conservation ranger, colorful nature illustration, flat design',
    ['nature', 'conservation', 'animals', 'plants', 'ecosystems'],
    'Our Natural World',
    ['What Is an Ecosystem?', 'Forests and Rainforests', 'Oceans and Marine Life', 'Grasslands and Savanna', 'Polar Regions', 'Rivers and Wetlands'],
    'Ecosystems Quiz',
    'Protecting What We Love',
    ['What Is Biodiversity?', 'Endangered Species', 'Habitat Destruction', 'How Conservation Works', 'National Parks and Protected Areas', 'What You Can Do to Help'],
    'Conservation Action Quiz',
  ),
  makeSkillsCourse(
    'sustainability-green-living',
    'Sustainability & Green Living',
    'environment',
    'elementary',
    'Learn practical ways to live sustainably: reduce waste, save energy, eat eco-friendly, and understand why every action counts.',
    'eco-friendly home with solar panels, recycling bins, green plants and energy saving devices, sustainability illustration, flat design',
    ['sustainability', 'green living', 'recycling', 'energy saving', 'eco-friendly'],
    'Understanding Sustainability',
    ['What Is Sustainability?', 'The Three Rs — Reduce, Reuse, Recycle', 'Energy and Where It Comes From', 'Renewable Energy Sources', 'Food and the Environment', 'Fast Fashion and Waste'],
    'Sustainability Basics Quiz',
    'Living Green Every Day',
    ['Reducing Your Carbon Footprint', 'Sustainable Shopping', 'Growing Your Own Food', 'Saving Water at Home', 'Green Transportation', 'Talking to Others About Sustainability'],
    'Green Living Quiz',
  ),
  makeSkillsCourse(
    'climate-action-solutions',
    'Climate Action & Solutions',
    'environment',
    'secondary',
    'Understand the climate crisis in depth and explore real technological, political, and personal solutions being implemented around the world.',
    'split illustration showing climate change impact on one side and green solutions on the other, hopeful environmental illustration, flat design',
    ['climate action', 'climate change', 'solutions', 'renewable energy', 'policy'],
    'The Climate Crisis',
    ['How Climate Change Works', 'Evidence from Science', 'Tipping Points', 'Climate Justice', 'How Nations Are Responding', 'The Paris Agreement'],
    'Climate Science Quiz',
    'Solutions and Action',
    ['Renewable Energy at Scale', 'Carbon Capture Technology', 'Sustainable Cities', 'Policy and Activism', 'Youth Climate Movements', 'Your Personal Climate Action'],
    'Climate Solutions Quiz',
  ),
  makeSkillsCourse(
    'environmental-engineering',
    'Environmental Engineering',
    'environment',
    'advanced',
    'Apply engineering principles to environmental challenges: water treatment, pollution control, renewable energy systems, and sustainable design.',
    'engineer designing green sustainable infrastructure with wind turbines, solar panels and water treatment systems, flat design illustration',
    ['environmental engineering', 'sustainable design', 'water treatment', 'pollution control', 'green technology'],
    'Foundations of Environmental Engineering',
    ['What Do Environmental Engineers Do?', 'Water Treatment Systems', 'Air Pollution Control', 'Waste Management Engineering', 'Soil Remediation', 'Environmental Impact Assessment'],
    'Environmental Engineering Basics Quiz',
    'Sustainable Systems Design',
    ['Renewable Energy Systems', 'Green Building Design', 'Sustainable Urban Planning', 'Climate Engineering', 'Life Cycle Assessment', 'Case Studies in Environmental Engineering'],
    'Sustainable Design Quiz',
  ),
];

// ── STEM Special Topics (6 courses) ──────────────────────────────────────────

export const STEM_SPECIAL_COURSES: CourseDefinition[] = [
  makeSkillsCourse(
    'engineering-for-kids',
    'Engineering for Kids',
    'stem-special',
    'juniors',
    'Discover the exciting world of engineering through hands-on thinking, design challenges, and real-world problem solving for young learners.',
    'young kids building and constructing with blocks, gears and engineering tools, colorful fun STEM illustration, flat design',
    ['engineering', 'design', 'problem solving', 'STEM', 'building'],
    'What Do Engineers Do?',
    ['Engineers Change the World', 'Civil Engineering — Building Things', 'Mechanical Engineering — How Machines Work', 'Electrical Engineering Basics', 'The Engineering Design Process', 'Famous Engineers in History'],
    'Engineering Basics Quiz',
    'Design Challenges',
    ['Bridges — Strong and Light', 'Towers — Tall and Stable', 'Machines and Simple Mechanisms', 'Water and Hydraulics', 'Engineering with Nature', 'Your Own Design Project'],
    'Design Thinking Quiz',
  ),
  makeSkillsCourse(
    'architecture-design',
    'Architecture & Design',
    'stem-special',
    'secondary',
    'Explore the art and science of architecture — from ancient wonders to modern skyscrapers — and learn the principles of great design.',
    'stunning architectural collage with classical and modern buildings, blueprints and design tools, flat design illustration',
    ['architecture', 'design', 'buildings', 'urban planning', 'interior design'],
    'Architecture Through History',
    ['What Is Architecture?', 'Ancient Architecture', 'Medieval Cathedrals and Castles', 'Renaissance and Baroque', 'Industrial Revolution and Iron', 'Modernism and Contemporary Design'],
    'Architectural History Quiz',
    'Design Principles and Process',
    ['Space, Form and Function', 'Structural Engineering Basics', 'Sustainable Architecture', 'Urban Planning and Cities', 'Interior Design', 'How Buildings Are Designed Today'],
    'Architecture Design Quiz',
  ),
  makeSkillsCourse(
    'marine-science',
    'Marine Science',
    'stem-special',
    'middle',
    'Dive into ocean science: explore marine ecosystems, ocean chemistry, fascinating sea creatures, coral reefs, and the threats facing our oceans.',
    'underwater ocean scene with diverse marine life, coral reefs, fish and ocean explorer, beautiful illustrated flat design',
    ['marine science', 'oceanography', 'marine biology', 'ocean ecosystems', 'conservation'],
    'The Ocean World',
    ['How Big Is the Ocean?', 'Ocean Zones and Depth', 'Ocean Chemistry', 'Marine Ecosystems', 'Coral Reefs', 'Deep Sea Wonders'],
    'Marine Science Basics Quiz',
    'Marine Life and Conservation',
    ['Fish and Marine Vertebrates', 'Marine Invertebrates', 'Marine Mammals', 'Sharks and Rays', 'Ocean Threats and Pollution', 'Marine Conservation'],
    'Marine Biology Quiz',
  ),
  makeSkillsCourse(
    'astronomy-astrophysics',
    'Astronomy & Astrophysics',
    'stem-special',
    'secondary',
    'Journey through the cosmos: stars, galaxies, black holes, the Big Bang, space exploration, and the latest discoveries in modern astrophysics.',
    'stunning night sky with galaxies, stars, planets and a telescope, epic universe illustration, flat design',
    ['astronomy', 'astrophysics', 'space', 'stars', 'galaxies', 'cosmology'],
    'Stars and Galaxies',
    ['The Scale of the Universe', 'How Stars Form and Die', 'Types of Stars', 'Our Galaxy — the Milky Way', 'Galaxies and Galaxy Clusters', 'Black Holes and Neutron Stars'],
    'Stellar Astronomy Quiz',
    'The Universe and Space Exploration',
    ['The Big Bang Theory', 'Dark Matter and Dark Energy', 'Exoplanets and the Search for Life', 'History of Space Exploration', 'Modern Space Missions', 'The Future of Astronomy'],
    'Astrophysics Quiz',
  ),
  makeSkillsCourse(
    'forensic-science',
    'Forensic Science',
    'stem-special',
    'secondary',
    'Apply science to solve crimes! Learn about DNA evidence, fingerprinting, toxicology, crime scene investigation, and forensic psychology.',
    'forensic investigator examining evidence in a lab with test tubes, fingerprints and magnifying glass, CSI style flat design illustration',
    ['forensic science', 'crime scene investigation', 'DNA', 'fingerprinting', 'forensic psychology'],
    'Crime Scene Investigation',
    ['What Is Forensic Science?', 'The Crime Scene', 'Evidence Collection and Preservation', 'Fingerprint Analysis', 'Hair and Fibre Evidence', 'Document and Digital Forensics'],
    'CSI Basics Quiz',
    'Scientific Analysis',
    ['DNA Profiling', 'Blood Spatter Analysis', 'Toxicology and Poisons', 'Forensic Pathology', 'Forensic Psychology', 'Famous Cases Solved by Science'],
    'Forensic Analysis Quiz',
  ),
  makeSkillsCourse(
    'medical-science-health',
    'Medical Science & Health',
    'stem-special',
    'secondary',
    'Explore the science of medicine: anatomy, disease, diagnosis, treatment, medical technology, and the history of healthcare.',
    'doctor with stethoscope and medical diagrams, human anatomy and healthcare technology illustration, flat design',
    ['medical science', 'anatomy', 'medicine', 'healthcare', 'biology'],
    'The Human Body and Disease',
    ['How the Body Systems Work Together', 'The Immune System', 'Infectious Diseases', 'Chronic Disease and Prevention', 'Genetics and Inherited Conditions', 'Mental Health as Medical'],
    'Medical Science Basics Quiz',
    'Diagnosis, Treatment and Technology',
    ['How Doctors Diagnose', 'Medications and How They Work', 'Surgery and Anaesthesia', 'Medical Imaging Technology', 'Public Health and Epidemiology', 'The Future of Medicine'],
    'Medical Technology Quiz',
  ),
];

// ── Combined export ──────────────────────────────────────────────────────────

export const SKILLS_COURSES: CourseDefinition[] = [
  ...LIFE_SKILLS_COURSES,
  ...PE_HEALTH_COURSES,
  ...WORLD_CULTURES_COURSES,
  ...ENVIRONMENT_COURSES,
  ...STEM_SPECIAL_COURSES,
];
