import type { CourseDefinition } from '../types.js';

export const TECHNOLOGY_COURSES: CourseDefinition[] = [
  // ═══════════════════════════════════════════════════════════
  // AI & MACHINE LEARNING (8 courses)
  // ═══════════════════════════════════════════════════════════
  {
    title: 'AI Explorers: Friendly Robots & Smart Machines',
    slug: 'ai-explorers',
    description: 'Discover the amazing world of Artificial Intelligence! Learn about friendly robots, how computers can think, and fun AI experiments — perfect for young learners.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'juniors',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Friendly cartoon robot with big eyes giving a thumbs up, surrounded by colorful gears and stars, flat design for young children, bright colors, no text',
    tags: ['ai', 'robots', 'beginners', 'age-6-8', 'technology'],
    sections: [
      {
        title: 'What is AI?',
        lessons: [
          { title: 'What Are Robots and Computers?', topic: 'Introduction to computers and robots as tools made by humans', order: 1 },
          { title: 'Computers That Learn!', topic: 'How AI is different from regular programs — it learns from experience', order: 2 },
          { title: 'AI in Your Everyday Life', topic: 'AI in smartphones, toys, games, and home devices kids use daily', order: 3 },
        ],
        quizzes: [{ title: 'What Do You Know About AI?', order: 1, questionCount: 5 }],
      },
      {
        title: 'How AI Thinks',
        lessons: [
          { title: 'Sorting & Patterns: How AI Sees', topic: 'Pattern recognition — how AI identifies shapes, colors, and objects', order: 4 },
          { title: 'Teaching a Computer with Examples', topic: 'Introduction to training — giving computers lots of examples to learn from', order: 5 },
          { title: 'AI Makes Mistakes Too!', topic: 'When AI gets things wrong and why — errors, bias, and improving AI', order: 6 },
        ],
        quizzes: [],
      },
      {
        title: 'AI in the Real World',
        lessons: [
          { title: 'AI That Talks to You', topic: 'Voice assistants like Siri, Alexa — how speech recognition works', order: 7 },
          { title: 'AI That Recognizes Faces', topic: 'Face recognition in phones and cameras — simple explanation for kids', order: 8 },
          { title: 'AI Animals: Robots That Move Like Animals', topic: 'Boston Dynamics robots and bio-inspired AI robots', order: 9 },
          { title: 'Be an AI Engineer!', topic: 'What AI engineers do and how kids can start learning', order: 10 },
        ],
        quizzes: [{ title: 'AI Explorer Certificate Quiz', order: 2, questionCount: 8 }],
      },
    ],
  },
  {
    title: 'AI Adventurers: Discovering How AI Works',
    slug: 'ai-adventurers',
    description: 'Go deeper into AI! Learn how machine learning works, explore image recognition, chatbots, and discover the ethics of AI.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'elementary',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Excited child explorer with magnifying glass discovering AI icons — neural network, data streams, robot — colorful flat design, no text',
    tags: ['ai', 'machine-learning', 'age-9-11', 'intermediate'],
    sections: [
      {
        title: 'Machine Learning Basics',
        lessons: [
          { title: 'What is Machine Learning?', topic: 'Definition of ML, difference from traditional programming, real examples', order: 1 },
          { title: 'Training Data: Food for AI', topic: 'How AI needs large amounts of data to learn patterns', order: 2 },
          { title: 'Supervised vs Unsupervised Learning', topic: 'Two main types of ML explained with everyday analogies', order: 3 },
          { title: 'Classification: Sorting Things Into Groups', topic: 'How AI classifies email as spam, images as cats/dogs, etc.', order: 4 },
        ],
        quizzes: [{ title: 'Machine Learning Checkpoint', order: 1, questionCount: 6 }],
      },
      {
        title: 'AI in Action',
        lessons: [
          { title: 'How Image Recognition Works', topic: 'Convolutional neural networks explained visually for kids', order: 5 },
          { title: 'Natural Language Processing: AI That Reads', topic: 'How AI understands text and language — sentiment analysis, translation', order: 6 },
          { title: 'Recommendation Systems', topic: 'How YouTube, Netflix, Spotify suggest what to watch/listen next', order: 7 },
          { title: 'AI in Games', topic: 'How game AI works — chess engines, NPCs, procedural generation', order: 8 },
        ],
        quizzes: [],
      },
      {
        title: 'Ethical AI',
        lessons: [
          { title: 'Is AI Always Fair?', topic: 'Bias in AI, fairness, and why diverse training data matters', order: 9 },
          { title: 'Privacy and AI', topic: 'How AI collects and uses personal data — privacy considerations for kids', order: 10 },
          { title: 'AI for Good: Solving World Problems', topic: 'AI helping climate, medicine, and education', order: 11 },
          { title: 'Your AI Future', topic: 'Careers in AI and what students can do to prepare', order: 12 },
        ],
        quizzes: [{ title: 'AI Adventurers Final Quiz', order: 2, questionCount: 10 }],
      },
    ],
  },
  {
    title: 'AI Builders: Creating with Python and AI',
    slug: 'ai-builders',
    description: 'Start building AI projects with Python! Implement decision trees, simple neural networks, and explore real machine learning libraries.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'middle',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Young student building AI robot with Python code on screen, gears and neural network diagram, colorful flat design, no text',
    tags: ['ai', 'python', 'machine-learning', 'age-12-14', 'hands-on'],
    sections: [
      {
        title: 'Python for AI',
        lessons: [
          { title: 'Python Refresher for AI', topic: 'Variables, lists, loops, and functions — Python essentials for ML', order: 1, includesCode: true, programmingLanguage: 'python' },
          { title: 'NumPy: Numbers Made Fast', topic: 'Introduction to NumPy arrays, operations, and why they are used in AI', order: 2, includesCode: true, programmingLanguage: 'python' },
          { title: 'Pandas: Working with Data', topic: 'Loading, exploring, and cleaning datasets with Pandas', order: 3, includesCode: true, programmingLanguage: 'python' },
          { title: 'Matplotlib: Visualizing Data', topic: 'Creating charts and plots to understand datasets', order: 4, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'Python for AI Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Machine Learning with scikit-learn',
        lessons: [
          { title: 'Your First ML Model: Linear Regression', topic: 'Predicting values with linear regression — house prices, temperatures', order: 5, includesCode: true, programmingLanguage: 'python' },
          { title: 'Decision Trees: How AI Makes Decisions', topic: 'Building and visualizing decision tree classifiers', order: 6, includesCode: true, programmingLanguage: 'python' },
          { title: 'K-Nearest Neighbors: Similarity Matching', topic: 'Classification by similarity — recommenders and pattern matching', order: 7, includesCode: true, programmingLanguage: 'python' },
          { title: 'Evaluating Your Model: Is It Good?', topic: 'Accuracy, precision, recall — how to measure ML performance', order: 8, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [],
      },
      {
        title: 'Neural Networks Introduction',
        lessons: [
          { title: 'What Are Neural Networks?', topic: 'Neurons, layers, weights — the building blocks of deep learning', order: 9 },
          { title: 'Building a Simple Neural Network', topic: 'Using TensorFlow/Keras to build a basic image classifier', order: 10, includesCode: true, programmingLanguage: 'python' },
          { title: 'Training and Testing Your Network', topic: 'Epochs, batches, training loops, and testing accuracy', order: 11, includesCode: true, programmingLanguage: 'python' },
          { title: 'Your AI Project: Image Classifier', topic: 'Complete project — train a model to classify images from scratch', order: 12, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'AI Builders Final Assessment', order: 2, questionCount: 10 }],
      },
    ],
  },
  {
    title: 'AI Engineers: Deep Learning & Real-World AI',
    slug: 'ai-engineers',
    description: 'Master advanced AI concepts — deep learning, NLP, computer vision, and deploying AI models. Build real-world AI projects.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'advanced',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Advanced neural network diagram with glowing nodes and connections, data flowing through layers, professional but colorful, flat design, no text',
    tags: ['ai', 'deep-learning', 'nlp', 'computer-vision', 'age-15-18', 'advanced'],
    sections: [
      {
        title: 'Deep Learning Fundamentals',
        lessons: [
          { title: 'Deep Learning Architecture Overview', topic: 'CNNs, RNNs, Transformers — the landscape of modern DL', order: 1 },
          { title: 'Convolutional Neural Networks (CNNs)', topic: 'Building CNNs for image classification with TensorFlow/Keras', order: 2, includesCode: true, programmingLanguage: 'python' },
          { title: 'Transfer Learning: Reusing Pre-trained Models', topic: 'Fine-tuning ResNet, VGG, MobileNet for custom tasks', order: 3, includesCode: true, programmingLanguage: 'python' },
          { title: 'Recurrent Neural Networks & LSTMs', topic: 'Sequence modeling for time series and text', order: 4, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'Deep Learning Foundations Quiz', order: 1, questionCount: 10 }],
      },
      {
        title: 'Natural Language Processing',
        lessons: [
          { title: 'NLP Fundamentals: Tokenization & Embeddings', topic: 'Text preprocessing, word vectors, and semantic meaning', order: 5, includesCode: true, programmingLanguage: 'python' },
          { title: 'The Transformer Revolution', topic: 'Attention mechanism, BERT, GPT — how large language models work', order: 6 },
          { title: 'Building a Chatbot', topic: 'Simple retrieval and generative chatbot with HuggingFace Transformers', order: 7, includesCode: true, programmingLanguage: 'python' },
          { title: 'Sentiment Analysis Project', topic: 'Build a product review sentiment analyzer from scratch', order: 8, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [],
      },
      {
        title: 'Computer Vision & AI Deployment',
        lessons: [
          { title: 'Object Detection with YOLO', topic: 'Real-time object detection, bounding boxes, confidence scores', order: 9, includesCode: true, programmingLanguage: 'python' },
          { title: 'Generative AI & GANs', topic: 'How AI generates images — GAN architecture and examples', order: 10 },
          { title: 'Deploying AI Models with FastAPI', topic: 'Building a REST API to serve ML predictions', order: 11, includesCode: true, programmingLanguage: 'python' },
          { title: 'AI Ethics & Responsible Development', topic: 'Bias, explainability, safety, and ethical AI engineering practices', order: 12 },
          { title: 'Capstone: Your AI Application', topic: 'End-to-end project — define problem, collect data, train, deploy', order: 13, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'AI Engineer Certification Exam', order: 2, questionCount: 15 }],
      },
    ],
  },
  {
    title: 'Machine Learning Fundamentals',
    slug: 'machine-learning-fundamentals',
    description: 'A comprehensive deep-dive into machine learning algorithms, mathematics, and practical implementation for advanced students.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'advanced',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Mathematical equations and ML algorithm flowcharts with colorful nodes and arrows, academic but engaging flat design, no text',
    tags: ['machine-learning', 'algorithms', 'mathematics', 'age-15-18'],
    sections: [
      {
        title: 'ML Mathematics',
        lessons: [
          { title: 'Linear Algebra for ML', topic: 'Vectors, matrices, operations used in machine learning', order: 1, includesCode: true, programmingLanguage: 'python' },
          { title: 'Calculus for ML: Gradients', topic: 'Derivatives, partial derivatives, and gradient descent intuition', order: 2 },
          { title: 'Statistics & Probability for ML', topic: 'Distributions, Bayes theorem, statistical significance', order: 3 },
          { title: 'Cost Functions & Optimization', topic: 'MSE, cross-entropy, SGD, Adam — optimization deep dive', order: 4, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'ML Mathematics Quiz', order: 1, questionCount: 10 }],
      },
      {
        title: 'Core Algorithms',
        lessons: [
          { title: 'Regression Algorithms', topic: 'Linear, polynomial, ridge, lasso regression from scratch', order: 5, includesCode: true, programmingLanguage: 'python' },
          { title: 'Classification Algorithms', topic: 'Logistic regression, SVM, Naive Bayes implementation', order: 6, includesCode: true, programmingLanguage: 'python' },
          { title: 'Ensemble Methods', topic: 'Random forests, gradient boosting, XGBoost', order: 7, includesCode: true, programmingLanguage: 'python' },
          { title: 'Unsupervised Learning', topic: 'K-means, DBSCAN, PCA, autoencoders', order: 8, includesCode: true, programmingLanguage: 'python' },
          { title: 'Reinforcement Learning Introduction', topic: 'Q-learning, reward functions, building a simple game-playing agent', order: 9, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [],
      },
      {
        title: 'Production ML',
        lessons: [
          { title: 'Feature Engineering & Selection', topic: 'Creating powerful features from raw data', order: 10, includesCode: true, programmingLanguage: 'python' },
          { title: 'Model Evaluation & Validation', topic: 'Cross-validation, ROC curves, confusion matrices', order: 11, includesCode: true, programmingLanguage: 'python' },
          { title: 'ML Pipelines with scikit-learn', topic: 'Building reproducible, production-ready ML pipelines', order: 12, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'ML Fundamentals Certification', order: 2, questionCount: 15 }],
      },
    ],
  },
  {
    title: 'Data Science & Analytics',
    slug: 'data-science-analytics',
    description: 'Learn to collect, analyze, visualize, and draw insights from data using Python, Pandas, and modern data tools.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'advanced',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Colorful data dashboards and charts floating around a young data scientist, bar charts, scatter plots, pie charts, flat design, no text',
    tags: ['data-science', 'analytics', 'python', 'age-15-18'],
    sections: [
      {
        title: 'Data Collection & Cleaning',
        lessons: [
          { title: 'Introduction to Data Science', topic: 'What data scientists do, tools of the trade, career paths', order: 1 },
          { title: 'Data Collection: APIs, CSVs & Web Scraping', topic: 'Fetching data from APIs and websites with Python', order: 2, includesCode: true, programmingLanguage: 'python' },
          { title: 'Data Cleaning with Pandas', topic: 'Handling missing values, duplicates, type conversion', order: 3, includesCode: true, programmingLanguage: 'python' },
          { title: 'Exploratory Data Analysis (EDA)', topic: 'Descriptive statistics, distributions, correlations', order: 4, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'Data Wrangling Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Visualization & Analysis',
        lessons: [
          { title: 'Data Visualization with Matplotlib & Seaborn', topic: 'Creating beautiful, informative charts', order: 5, includesCode: true, programmingLanguage: 'python' },
          { title: 'Interactive Dashboards with Plotly', topic: 'Building interactive web dashboards for data stories', order: 6, includesCode: true, programmingLanguage: 'python' },
          { title: 'Statistical Analysis & Hypothesis Testing', topic: 'A/B testing, t-tests, chi-square — making data-driven decisions', order: 7, includesCode: true, programmingLanguage: 'python' },
          { title: 'Time Series Analysis', topic: 'Analyzing trends and seasonality in time-based data', order: 8, includesCode: true, programmingLanguage: 'python' },
          { title: 'SQL for Data Analysis', topic: 'Querying databases for data analysis', order: 9, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [],
      },
      {
        title: 'Data Science Projects',
        lessons: [
          { title: 'Capstone: Sports Analytics Dashboard', topic: 'Analyze real sports data, build insights, create visualizations', order: 10, includesCode: true, programmingLanguage: 'python' },
          { title: 'Capstone: Social Media Analytics', topic: 'Sentiment and trend analysis on social media data', order: 11, includesCode: true, programmingLanguage: 'python' },
          { title: 'Data Storytelling & Presenting Insights', topic: 'Communicating data findings effectively to non-technical audiences', order: 12 },
        ],
        quizzes: [{ title: 'Data Science Certification', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'Robotics & AI',
    slug: 'robotics-ai',
    description: 'Build and program robots! Learn robotics fundamentals, sensors, actuators, and AI-powered robot behaviors.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'middle',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Colorful robot with arms and sensors, circuit board background, gears and wheels, fun and engaging flat design for middle school, no text',
    tags: ['robotics', 'ai', 'engineering', 'age-12-14'],
    sections: [
      {
        title: 'Robotics Foundations',
        lessons: [
          { title: 'What is a Robot?', topic: 'Definition, types of robots, history of robotics from ancient to modern', order: 1 },
          { title: 'Robot Components: Sensors & Actuators', topic: 'How robots sense their environment and take action', order: 2 },
          { title: 'Robot Movement & Kinematics', topic: 'How robots move — wheels, joints, arms, and degrees of freedom', order: 3 },
          { title: 'Programming a Robot with Python', topic: 'Introduction to robot programming using Python and simulation', order: 4, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'Robotics Basics Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'AI for Robots',
        lessons: [
          { title: 'Computer Vision for Robots', topic: 'Using cameras and image processing for robot navigation', order: 5 },
          { title: 'Path Planning Algorithms', topic: 'How robots find their way — A*, Dijkstra, RRT algorithms', order: 6 },
          { title: 'Robot Learning: Reinforcement Learning', topic: 'Teaching robots through trial and reward', order: 7, includesCode: true, programmingLanguage: 'python' },
          { title: 'Human-Robot Interaction', topic: 'Designing robots that work safely and naturally with humans', order: 8 },
          { title: 'Real Robots: Case Studies', topic: 'Mars rovers, surgical robots, autonomous vehicles, drones', order: 9 },
        ],
        quizzes: [],
      },
      {
        title: 'Robotics Projects',
        lessons: [
          { title: 'Simulate Your Robot with Webots', topic: 'Using the Webots simulator to build and test virtual robots', order: 10, includesCode: true, programmingLanguage: 'python' },
          { title: 'Build a Line-Following Robot', topic: 'Project: program a simulated line-following robot', order: 11, includesCode: true, programmingLanguage: 'python' },
          { title: 'The Future of Robotics', topic: 'Soft robotics, swarm robotics, nanorobots — the frontier of the field', order: 12 },
        ],
        quizzes: [{ title: 'Robotics & AI Certificate Exam', order: 2, questionCount: 10 }],
      },
    ],
  },
  {
    title: 'AI Ethics & Society',
    slug: 'ai-ethics-society',
    description: 'Explore the profound impact of AI on society — bias, privacy, democracy, jobs, and how to build AI responsibly.',
    categorySlug: 'ai-machine-learning',
    ageGroup: 'advanced',
    type: 'ai',
    hasCertification: true,
    imagePrompt: 'Scales of justice balanced with AI robot and human, thoughtful blue and green colors, flat design, ethical technology imagery, no text',
    tags: ['ai-ethics', 'society', 'technology-impact', 'age-15-18'],
    sections: [
      {
        title: 'AI and Human Values',
        lessons: [
          { title: 'The Ethics of Artificial Intelligence', topic: 'What are AI ethics and why they matter in modern society', order: 1 },
          { title: 'Algorithmic Bias: When AI Discriminates', topic: 'Case studies of biased AI in hiring, criminal justice, lending', order: 2 },
          { title: 'Fairness in Machine Learning', topic: 'Mathematical definitions of fairness and their trade-offs', order: 3 },
          { title: 'AI and Privacy', topic: 'Surveillance, facial recognition, data collection and consent', order: 4 },
        ],
        quizzes: [{ title: 'AI Ethics Foundations Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'AI and Society',
        lessons: [
          { title: 'AI and the Future of Work', topic: 'Job automation, economic disruption, and new opportunities AI creates', order: 5 },
          { title: 'AI and Democracy', topic: 'Deepfakes, misinformation, filter bubbles, and political manipulation', order: 6 },
          { title: 'AI in Healthcare: Promise and Peril', topic: 'Medical AI success stories and failures — diagnostic tools, drug discovery', order: 7 },
          { title: 'AI Weapons and Military Ethics', topic: 'Autonomous weapons, lethal AI, and international governance', order: 8 },
        ],
        quizzes: [],
      },
      {
        title: 'Building Responsible AI',
        lessons: [
          { title: 'Explainable AI (XAI)', topic: 'Making AI decisions interpretable and accountable', order: 9 },
          { title: 'AI Governance and Regulation', topic: 'EU AI Act, global governance frameworks, industry standards', order: 10 },
          { title: 'Designing Ethical AI Systems', topic: 'Ethics by design — how engineers embed values into AI', order: 11 },
          { title: 'Your Role in the AI Future', topic: 'How students and young people can shape ethical AI development', order: 12 },
        ],
        quizzes: [{ title: 'AI Ethics & Society Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PROGRAMMING LANGUAGES (12 courses)
  // ═══════════════════════════════════════════════════════════
  {
    title: 'Code Starters: Learn with Scratch',
    slug: 'code-starters-scratch',
    description: 'Start your coding adventure with Scratch! Create stories, games, and animations using colorful blocks — no typing needed!',
    categorySlug: 'programming-languages',
    ageGroup: 'juniors',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Scratch cat mascot surrounded by colorful code blocks, sprites, and game elements, very bright and fun for young children, flat design, no text',
    tags: ['scratch', 'block-coding', 'beginners', 'age-6-8', 'visual-programming'],
    sections: [
      {
        title: 'Getting Started with Scratch',
        lessons: [
          { title: 'Welcome to Scratch!', topic: 'Introduction to the Scratch editor — sprites, stage, and blocks', order: 1 },
          { title: 'Making a Sprite Move', topic: 'Motion blocks — move steps, turn, go to position', order: 2, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Costumes and Looks', topic: 'Changing how sprites look with Looks blocks', order: 3, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Adding Sounds', topic: 'Sound blocks — playing music and sound effects', order: 4, includesCode: true, programmingLanguage: 'scratch' },
        ],
        quizzes: [{ title: 'Scratch Basics Quiz', order: 1, questionCount: 5 }],
      },
      {
        title: 'Events and Logic',
        lessons: [
          { title: 'Events: When Things Happen', topic: 'When green flag clicked, when key pressed, when sprite clicked', order: 5, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Loops: Repeat and Forever', topic: 'Repeat loops and forever loops to make things keep going', order: 6, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'If-Then: Making Decisions', topic: 'Conditional blocks — if this happens, do that', order: 7, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Variables: Remember Things', topic: 'Using variables to keep track of scores and game state', order: 8, includesCode: true, programmingLanguage: 'scratch' },
        ],
        quizzes: [],
      },
      {
        title: 'Fun Projects',
        lessons: [
          { title: 'Build an Animated Story', topic: 'Creating a multi-scene animated story with dialogue', order: 9, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Build a Catching Game', topic: 'Simple game where player catches falling objects', order: 10, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Build a Quiz Game', topic: 'Interactive quiz with score tracking using variables', order: 11, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Share Your Creation!', topic: 'Publishing projects, getting feedback, and the Scratch community', order: 12 },
        ],
        quizzes: [{ title: 'Scratch Coder Certificate', order: 2, questionCount: 8 }],
      },
    ],
  },
  {
    title: 'Block Coding & Computational Logic',
    slug: 'block-coding-logic',
    description: 'Master block-based coding with Scratch and App Inventor. Build logic skills that transfer to real programming.',
    categorySlug: 'programming-languages',
    ageGroup: 'elementary',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Colorful logic gates and block code pieces fitting together like puzzle, bright educational illustration, flat design, no text',
    tags: ['block-coding', 'scratch', 'app-inventor', 'logic', 'age-9-11'],
    sections: [
      {
        title: 'Advanced Scratch',
        lessons: [
          { title: 'Lists and Data Structures in Scratch', topic: 'Using lists to store multiple items — scores, names, inventory', order: 1, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Custom Blocks: Making Functions', topic: 'Creating reusable blocks for cleaner code', order: 2, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Cloning: Create Multiple Sprites', topic: 'Using clones to create many objects from one sprite', order: 3, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Build a Platformer Game', topic: 'Complete platformer with gravity, jumping, and platforms', order: 4, includesCode: true, programmingLanguage: 'scratch' },
        ],
        quizzes: [{ title: 'Advanced Scratch Quiz', order: 1, questionCount: 6 }],
      },
      {
        title: 'MIT App Inventor',
        lessons: [
          { title: 'Introduction to App Inventor', topic: 'Building real Android apps with blocks — the MIT App Inventor environment', order: 5 },
          { title: 'Your First App: Button Clicker', topic: 'UI components, events, and basic app logic in App Inventor', order: 6, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Build a Quiz App', topic: 'Multi-screen app with questions, answers, and scoring', order: 7, includesCode: true, programmingLanguage: 'scratch' },
          { title: 'Build a Drawing App', topic: 'Canvas component, touch events, drawing with your finger', order: 8, includesCode: true, programmingLanguage: 'scratch' },
        ],
        quizzes: [],
      },
      {
        title: 'Computational Thinking',
        lessons: [
          { title: 'Decomposition: Breaking Problems Down', topic: 'The computational thinking skill of breaking big problems into smaller parts', order: 9 },
          { title: 'Algorithms: Step-by-Step Solutions', topic: 'Writing algorithms before coding — flowcharts and pseudocode', order: 10 },
          { title: 'Pattern Recognition in Programming', topic: 'Finding repeating patterns and using loops/functions effectively', order: 11 },
          { title: 'Debugging: Finding and Fixing Errors', topic: 'Systematic approaches to finding bugs in block code', order: 12 },
        ],
        quizzes: [{ title: 'Block Coding & Logic Certificate', order: 2, questionCount: 8 }],
      },
    ],
  },
  {
    title: 'Python Juniors: Your First Real Programming Language',
    slug: 'python-juniors',
    description: 'Jump into Python — the world\'s most beginner-friendly programming language! Print, calculate, draw, and build your first programs.',
    categorySlug: 'programming-languages',
    ageGroup: 'elementary',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Python snake mascot wearing graduation cap with Python logo, colorful code output on screen, friendly illustration for kids, flat design, no text',
    tags: ['python', 'beginners', 'age-9-11', 'programming'],
    sections: [
      {
        title: 'Python Basics',
        lessons: [
          { title: 'What is Python and Why Learn It?', topic: 'Python overview, why it is popular, what you can build with it', order: 1 },
          { title: 'Your First Python Program', topic: 'Hello World, print() function, running Python in IDLE/Replit', order: 2, includesCode: true, programmingLanguage: 'python' },
          { title: 'Variables and Data Types', topic: 'Strings, integers, floats, booleans — storing information in Python', order: 3, includesCode: true, programmingLanguage: 'python' },
          { title: 'User Input and Output', topic: 'input() and print() — making interactive programs', order: 4, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'Python Basics Quiz', order: 1, questionCount: 6 }],
      },
      {
        title: 'Logic and Loops',
        lessons: [
          { title: 'If, Elif, Else: Making Decisions', topic: 'Conditional statements and comparison operators', order: 5, includesCode: true, programmingLanguage: 'python' },
          { title: 'For Loops: Repeating Things', topic: 'Iterating over ranges and lists with for loops', order: 6, includesCode: true, programmingLanguage: 'python' },
          { title: 'While Loops: Keep Going Until', topic: 'While loop for unknown repetitions, break and continue', order: 7, includesCode: true, programmingLanguage: 'python' },
          { title: 'Lists: Storing Multiple Items', topic: 'Creating, accessing, and modifying Python lists', order: 8, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [],
      },
      {
        title: 'Functions and Projects',
        lessons: [
          { title: 'Functions: Reusable Code Blocks', topic: 'Defining and calling functions with parameters and return values', order: 9, includesCode: true, programmingLanguage: 'python' },
          { title: 'Math with Python', topic: 'Math library, operators, building a calculator app', order: 10, includesCode: true, programmingLanguage: 'python' },
          { title: 'Drawing with Turtle', topic: 'Using Python turtle graphics to draw shapes and patterns', order: 11, includesCode: true, programmingLanguage: 'python' },
          { title: 'Mini Project: Number Guessing Game', topic: 'Complete game using all concepts: variables, loops, if/else, functions', order: 12, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'Python Juniors Certificate', order: 2, questionCount: 10 }],
      },
    ],
  },
  {
    title: 'Python Advanced: Mastering the Language',
    slug: 'python-advanced',
    description: 'Level up your Python skills! Object-oriented programming, file handling, APIs, data structures, algorithms, and building real applications.',
    categorySlug: 'programming-languages',
    ageGroup: 'middle',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Advanced Python code with OOP diagrams, class hierarchies, colorful data structures, professional but engaging flat design for teens, no text',
    tags: ['python', 'oop', 'advanced', 'age-12-14', 'algorithms'],
    sections: [
      {
        title: 'Object-Oriented Python',
        lessons: [
          { title: 'Dictionaries and Sets', topic: 'Python dictionaries, sets, and their use cases', order: 1, includesCode: true, programmingLanguage: 'python' },
          { title: 'Object-Oriented Programming Introduction', topic: 'Classes, objects, attributes, and methods in Python', order: 2, includesCode: true, programmingLanguage: 'python' },
          { title: 'Inheritance and Polymorphism', topic: 'Extending classes, method overriding, polymorphic behavior', order: 3, includesCode: true, programmingLanguage: 'python' },
          { title: 'Magic Methods & Operator Overloading', topic: '__str__, __len__, __add__ and other dunder methods', order: 4, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'OOP Python Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Files, Errors & Modules',
        lessons: [
          { title: 'File Handling: Reading and Writing', topic: 'Open, read, write, close files — text and CSV', order: 5, includesCode: true, programmingLanguage: 'python' },
          { title: 'Exception Handling', topic: 'try/except/finally — handling errors gracefully', order: 6, includesCode: true, programmingLanguage: 'python' },
          { title: 'Python Modules and Packages', topic: 'Importing modules, pip, creating your own modules', order: 7, includesCode: true, programmingLanguage: 'python' },
          { title: 'Working with JSON and APIs', topic: 'Fetching and parsing JSON from REST APIs with requests library', order: 8, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [],
      },
      {
        title: 'Algorithms & Projects',
        lessons: [
          { title: 'Sorting Algorithms', topic: 'Bubble sort, insertion sort, merge sort implementation and comparison', order: 9, includesCode: true, programmingLanguage: 'python' },
          { title: 'Searching Algorithms', topic: 'Linear search, binary search — when to use each', order: 10, includesCode: true, programmingLanguage: 'python' },
          { title: 'Regular Expressions', topic: 'Pattern matching and text processing with regex', order: 11, includesCode: true, programmingLanguage: 'python' },
          { title: 'Project: Build a To-Do App', topic: 'Command-line task manager using OOP, files, and error handling', order: 12, includesCode: true, programmingLanguage: 'python' },
          { title: 'Project: Weather Dashboard', topic: 'Fetch real weather data from an API and display beautifully', order: 13, includesCode: true, programmingLanguage: 'python' },
        ],
        quizzes: [{ title: 'Python Advanced Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'JavaScript: Web\'s Most Popular Language',
    slug: 'javascript-essentials',
    description: 'Master JavaScript — the language that powers the web! From basics to DOM manipulation, events, and interactive web applications.',
    categorySlug: 'programming-languages',
    ageGroup: 'middle',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'JavaScript logo with colorful web browser and interactive UI elements floating around it, modern flat design for middle school, no text',
    tags: ['javascript', 'web', 'frontend', 'age-12-14', 'dom'],
    sections: [
      {
        title: 'JavaScript Fundamentals',
        lessons: [
          { title: 'Introduction to JavaScript', topic: 'What is JS, where it runs, setting up with browser console and VS Code', order: 1, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Variables: let, const, var', topic: 'Variable declaration, scope, hoisting, best practices', order: 2, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Data Types and Operators', topic: 'Strings, numbers, booleans, null, undefined, template literals', order: 3, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Functions: Classic and Arrow', topic: 'Function declarations, expressions, arrow functions, parameters, return', order: 4, includesCode: true, programmingLanguage: 'javascript' },
        ],
        quizzes: [{ title: 'JavaScript Basics Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Arrays, Objects and DOM',
        lessons: [
          { title: 'Arrays and Array Methods', topic: 'map, filter, reduce, forEach, find — the most useful array methods', order: 5, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Objects and JSON', topic: 'Object literals, properties, methods, destructuring, spread operator', order: 6, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'The DOM: Making Pages Interactive', topic: 'querySelector, getElementById, event listeners, changing HTML/CSS with JS', order: 7, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Events: Responding to User Actions', topic: 'Click, input, submit events, event delegation, preventing defaults', order: 8, includesCode: true, programmingLanguage: 'javascript' },
        ],
        quizzes: [],
      },
      {
        title: 'Async and Projects',
        lessons: [
          { title: 'Async JavaScript: Promises & Fetch', topic: 'Asynchronous code, promises, async/await, fetch API', order: 9, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Working with APIs', topic: 'Fetching JSON data from public APIs and displaying it', order: 10, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Local Storage & Session Storage', topic: 'Persisting data in the browser without a backend', order: 11, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Project: Interactive Quiz App', topic: 'Full quiz application with timer, scoring, and dynamic UI', order: 12, includesCode: true, programmingLanguage: 'javascript' },
        ],
        quizzes: [{ title: 'JavaScript Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'TypeScript: JavaScript Supercharged',
    slug: 'typescript-essentials',
    description: 'Learn TypeScript — the typed superset of JavaScript used by professional developers at Google, Microsoft, and Airbnb.',
    categorySlug: 'programming-languages',
    ageGroup: 'advanced',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'TypeScript logo with type annotations floating as colorful labels, professional code editor screenshot, flat design, no text',
    tags: ['typescript', 'javascript', 'types', 'age-15-18', 'professional'],
    sections: [
      {
        title: 'TypeScript Fundamentals',
        lessons: [
          { title: 'Why TypeScript? Static Typing Explained', topic: 'Type safety, catching bugs early, TypeScript vs JavaScript', order: 1, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'Types, Interfaces and Type Aliases', topic: 'Primitive types, interfaces, type aliases, union types, intersection', order: 2, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'Functions in TypeScript', topic: 'Typed parameters, return types, optional parameters, overloading', order: 3, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'Arrays, Tuples and Enums', topic: 'Typed arrays, readonly, tuples, and enum types', order: 4, includesCode: true, programmingLanguage: 'typescript' },
        ],
        quizzes: [{ title: 'TypeScript Basics Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Advanced Types',
        lessons: [
          { title: 'OOP in TypeScript', topic: 'Classes, access modifiers, abstract classes, interfaces', order: 5, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'Generics: Flexible Reusable Code', topic: 'Generic functions, generic classes, constraints, utility types', order: 6, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'Decorators', topic: 'Class, method, property decorators — metaprogramming in TypeScript', order: 7, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'TypeScript Configuration & Tooling', topic: 'tsconfig.json, ts-node, build tools, ESLint with TypeScript', order: 8, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'TypeScript with Node.js', topic: 'Building a typed Express API with TypeScript', order: 9, includesCode: true, programmingLanguage: 'typescript' },
        ],
        quizzes: [],
      },
      {
        title: 'Projects',
        lessons: [
          { title: 'TypeScript in the Real World', topic: 'TypeScript at top companies — codebases, conventions, best practices', order: 10 },
          { title: 'Project: Typed REST API', topic: 'Build a fully typed REST API with Express and TypeScript', order: 11, includesCode: true, programmingLanguage: 'typescript' },
          { title: 'Project: TypeScript React App', topic: 'Build a type-safe React application', order: 12, includesCode: true, programmingLanguage: 'typescript' },
        ],
        quizzes: [{ title: 'TypeScript Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'C# & .NET: Microsoft\'s Powerful Language',
    slug: 'csharp-dotnet',
    description: 'Learn C# — a versatile language used for games (Unity), enterprise software, and web development with .NET.',
    categorySlug: 'programming-languages',
    ageGroup: 'advanced',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'C# logo with .NET ecosystem icons, Unity game engine hint, colorful professional flat design for senior students, no text',
    tags: ['csharp', 'dotnet', 'unity', 'age-15-18', 'enterprise'],
    sections: [
      {
        title: 'C# Fundamentals',
        lessons: [
          { title: 'Introduction to C# and .NET', topic: 'C# history, .NET ecosystem, setting up Visual Studio / VS Code', order: 1, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'C# Syntax and Data Types', topic: 'Variables, data types, nullable types, var keyword', order: 2, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'Control Flow in C#', topic: 'if/else, switch expressions, for, foreach, while loops', order: 3, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'Methods and Parameters', topic: 'Method syntax, overloading, optional parameters, out/ref', order: 4, includesCode: true, programmingLanguage: 'csharp' },
        ],
        quizzes: [{ title: 'C# Basics Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Object-Oriented C#',
        lessons: [
          { title: 'Classes, Objects and Properties', topic: 'OOP fundamentals, auto-properties, constructors, this keyword', order: 5, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'Inheritance and Interfaces', topic: 'Base classes, derived classes, abstract classes, interfaces', order: 6, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'Generics and Collections', topic: 'List<T>, Dictionary<K,V>, LINQ basics', order: 7, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'Async/Await in C#', topic: 'Asynchronous programming, Task, async/await patterns', order: 8, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'LINQ: Query Your Data', topic: 'Language Integrated Query — filtering, sorting, transforming data', order: 9, includesCode: true, programmingLanguage: 'csharp' },
        ],
        quizzes: [],
      },
      {
        title: 'C# Projects',
        lessons: [
          { title: 'C# for Unity Game Development', topic: 'Using C# in Unity — GameObjects, Components, MonoBehaviour', order: 10, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'ASP.NET Core Web API', topic: 'Building a REST API with ASP.NET Core controllers', order: 11, includesCode: true, programmingLanguage: 'csharp' },
          { title: 'Project: Console RPG Game', topic: 'Text-based RPG using OOP, inheritance, and game state management', order: 12, includesCode: true, programmingLanguage: 'csharp' },
        ],
        quizzes: [{ title: 'C# & .NET Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'Java Programming: Enterprise & Android',
    slug: 'java-programming',
    description: 'Learn Java — one of the world\'s most widely used languages, powering enterprise applications, Android, and Spring Boot.',
    categorySlug: 'programming-languages',
    ageGroup: 'advanced',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Java coffee cup logo with Android robot and Spring leaf icon, enterprise code architecture diagram, colorful flat design, no text',
    tags: ['java', 'android', 'spring', 'age-15-18', 'enterprise'],
    sections: [
      {
        title: 'Java Foundations',
        lessons: [
          { title: 'Introduction to Java', topic: 'JVM, JDK, compilation, "Write Once Run Anywhere" philosophy', order: 1, includesCode: true, programmingLanguage: 'java' },
          { title: 'Java Syntax and Types', topic: 'Primitive types, reference types, type casting, String operations', order: 2, includesCode: true, programmingLanguage: 'java' },
          { title: 'OOP in Java', topic: 'Classes, constructors, getters/setters, encapsulation', order: 3, includesCode: true, programmingLanguage: 'java' },
          { title: 'Inheritance, Interfaces & Abstract Classes', topic: 'extends, implements, abstract — Java OOP hierarchy', order: 4, includesCode: true, programmingLanguage: 'java' },
        ],
        quizzes: [{ title: 'Java Fundamentals Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Java Collections & Advanced',
        lessons: [
          { title: 'Java Collections Framework', topic: 'ArrayList, HashMap, HashSet, LinkedList, TreeMap', order: 5, includesCode: true, programmingLanguage: 'java' },
          { title: 'Exception Handling in Java', topic: 'try/catch/finally, checked vs unchecked exceptions, custom exceptions', order: 6, includesCode: true, programmingLanguage: 'java' },
          { title: 'Generics in Java', topic: 'Generic classes, methods, bounded type parameters, wildcards', order: 7, includesCode: true, programmingLanguage: 'java' },
          { title: 'Java Streams & Lambdas', topic: 'Functional programming in Java — stream(), filter(), map(), collect()', order: 8, includesCode: true, programmingLanguage: 'java' },
          { title: 'Multithreading & Concurrency', topic: 'Threads, synchronization, ExecutorService, CompletableFuture', order: 9, includesCode: true, programmingLanguage: 'java' },
        ],
        quizzes: [],
      },
      {
        title: 'Java Applications',
        lessons: [
          { title: 'Spring Boot: Building REST APIs', topic: 'Spring framework, dependency injection, REST controllers, JPA', order: 10, includesCode: true, programmingLanguage: 'java' },
          { title: 'Java & Databases with JPA/Hibernate', topic: 'ORM, entities, repositories, CRUD operations', order: 11, includesCode: true, programmingLanguage: 'java' },
          { title: 'Project: Student Management API', topic: 'Full REST API for a school management system', order: 12, includesCode: true, programmingLanguage: 'java' },
        ],
        quizzes: [{ title: 'Java Programming Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'Node.js: Server-Side JavaScript',
    slug: 'nodejs-backend',
    description: 'Build powerful backend applications with Node.js! REST APIs, databases, authentication, and real-time apps with Socket.io.',
    categorySlug: 'programming-languages',
    ageGroup: 'advanced',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Node.js green logo with server icons, API endpoints, and database connections, modern backend development flat design, no text',
    tags: ['nodejs', 'backend', 'express', 'api', 'age-15-18'],
    sections: [
      {
        title: 'Node.js Fundamentals',
        lessons: [
          { title: 'Introduction to Node.js', topic: 'Event loop, non-blocking I/O, Node vs browser JS, npm', order: 1, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Modules: CommonJS and ESM', topic: 'require(), import/export, built-in modules (fs, path, http)', order: 2, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'npm and Package Management', topic: 'npm install, package.json, semver, scripts, devDependencies', order: 3, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Asynchronous Node: Callbacks to Async/Await', topic: 'Callback hell, Promises, async/await — Node.js async patterns', order: 4, includesCode: true, programmingLanguage: 'javascript' },
        ],
        quizzes: [{ title: 'Node.js Basics Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Express.js REST APIs',
        lessons: [
          { title: 'Express.js: Building Web Servers', topic: 'Routing, middleware, request/response, error handling', order: 5, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'REST API Design', topic: 'HTTP methods, status codes, RESTful principles, JSON responses', order: 6, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Database Integration: MongoDB with Mongoose', topic: 'NoSQL concepts, schemas, models, CRUD with Mongoose', order: 7, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Authentication with JWT', topic: 'User auth, bcrypt, JSON Web Tokens, protected routes', order: 8, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Input Validation & Security', topic: 'Joi/Zod validation, helmet, cors, rate limiting', order: 9, includesCode: true, programmingLanguage: 'javascript' },
        ],
        quizzes: [],
      },
      {
        title: 'Advanced Node.js',
        lessons: [
          { title: 'File Uploads with Multer', topic: 'Handling file uploads, image processing, cloud storage', order: 10, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Real-Time Apps with Socket.io', topic: 'WebSockets, rooms, events — building a real-time chat', order: 11, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Testing Node.js APIs with Jest', topic: 'Unit tests, integration tests, supertest for API testing', order: 12, includesCode: true, programmingLanguage: 'javascript' },
          { title: 'Deployment: Node.js to Production', topic: 'Environment variables, PM2, Docker basics, deploying to Render/Railway', order: 13, includesCode: true, programmingLanguage: 'javascript' },
        ],
        quizzes: [{ title: 'Node.js Backend Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'Go Language: Fast, Simple, Powerful',
    slug: 'go-programming',
    description: 'Learn Go (Golang) — the language behind Docker, Kubernetes, and high-performance cloud infrastructure at Google.',
    categorySlug: 'programming-languages',
    ageGroup: 'advanced',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Go Gopher mascot with cloud infrastructure icons, Docker containers, and server diagrams, colorful flat design, no text',
    tags: ['go', 'golang', 'cloud', 'performance', 'age-15-18'],
    sections: [
      {
        title: 'Go Basics',
        lessons: [
          { title: 'Introduction to Go', topic: 'Go philosophy, use cases, setting up Go workspace', order: 1, includesCode: true, programmingLanguage: 'go' },
          { title: 'Go Types and Variables', topic: 'Static typing, type inference, constants, zero values', order: 2, includesCode: true, programmingLanguage: 'go' },
          { title: 'Functions and Multiple Return Values', topic: 'Function syntax, multiple returns, named returns, defer', order: 3, includesCode: true, programmingLanguage: 'go' },
          { title: 'Structs and Methods', topic: 'Go structs as data structures, methods with receivers', order: 4, includesCode: true, programmingLanguage: 'go' },
        ],
        quizzes: [{ title: 'Go Fundamentals Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Go Concurrency',
        lessons: [
          { title: 'Slices, Maps and Arrays', topic: 'Go collection types, make(), range, nil handling', order: 5, includesCode: true, programmingLanguage: 'go' },
          { title: 'Interfaces in Go', topic: 'Interface definition, implicit implementation, empty interface', order: 6, includesCode: true, programmingLanguage: 'go' },
          { title: 'Error Handling in Go', topic: 'errors.New(), fmt.Errorf(), custom error types, wrapping errors', order: 7, includesCode: true, programmingLanguage: 'go' },
          { title: 'Goroutines and Channels', topic: 'Go concurrency model — goroutines, channels, select, WaitGroup', order: 8, includesCode: true, programmingLanguage: 'go' },
          { title: 'Building a REST API in Go', topic: 'net/http, routing with chi/gin, JSON encoding, middleware', order: 9, includesCode: true, programmingLanguage: 'go' },
        ],
        quizzes: [],
      },
      {
        title: 'Go Projects',
        lessons: [
          { title: 'Go Modules and Packages', topic: 'Go module system, go.mod, go.sum, importing packages', order: 10, includesCode: true, programmingLanguage: 'go' },
          { title: 'Testing in Go', topic: 'testing package, table-driven tests, benchmarking', order: 11, includesCode: true, programmingLanguage: 'go' },
          { title: 'Project: CLI Tool in Go', topic: 'Build a command-line utility with flags, arguments, and cobra', order: 12, includesCode: true, programmingLanguage: 'go' },
        ],
        quizzes: [{ title: 'Go Language Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'Rust: Systems Programming for the Future',
    slug: 'rust-programming',
    description: 'Learn Rust — the most loved programming language for systems programming, WebAssembly, and safe memory management.',
    categorySlug: 'programming-languages',
    ageGroup: 'advanced',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Rust crab mascot Ferris with memory safety shields, gear icons, and performance chart, colorful flat design, no text',
    tags: ['rust', 'systems-programming', 'wasm', 'age-16-18', 'advanced'],
    sections: [
      {
        title: 'Rust Foundations',
        lessons: [
          { title: 'Why Rust? Safety Without Garbage Collection', topic: 'Memory safety, performance, Rust use cases, cargo setup', order: 1, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Ownership: Rust\'s Superpower', topic: 'Ownership rules, move semantics, stack vs heap', order: 2, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Borrowing and References', topic: 'Immutable and mutable borrows, the borrow checker', order: 3, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Structs, Enums and Pattern Matching', topic: 'Rust data types, enum variants, match expressions, if let', order: 4, includesCode: true, programmingLanguage: 'rust' },
        ],
        quizzes: [{ title: 'Rust Ownership Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'Rust Collections & Traits',
        lessons: [
          { title: 'Collections: Vec, HashMap, HashSet', topic: 'Standard collections, iteration, Entry API', order: 5, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Traits: Rust\'s Interface System', topic: 'Defining and implementing traits, trait objects, generics', order: 6, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Error Handling with Result and Option', topic: 'Result<T,E>, Option<T>, ? operator, custom error types', order: 7, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Closures and Iterators', topic: 'Rust closures, iterator adapters, functional-style programming', order: 8, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Concurrency in Rust', topic: 'Thread safety, Arc, Mutex, Channels — fearless concurrency', order: 9, includesCode: true, programmingLanguage: 'rust' },
        ],
        quizzes: [],
      },
      {
        title: 'Rust Projects',
        lessons: [
          { title: 'Cargo, Crates and the Ecosystem', topic: 'Rust package manager, crates.io, popular libraries', order: 10, includesCode: true, programmingLanguage: 'rust' },
          { title: 'Building CLI Tools with clap', topic: 'Command-line application with argument parsing', order: 11, includesCode: true, programmingLanguage: 'rust' },
          { title: 'WebAssembly with Rust', topic: 'Compiling Rust to WASM, calling from JavaScript', order: 12, includesCode: true, programmingLanguage: 'rust' },
        ],
        quizzes: [{ title: 'Rust Programming Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
  {
    title: 'Swift: iOS and Mac Development',
    slug: 'swift-ios',
    description: 'Learn Swift and SwiftUI to build beautiful iOS and macOS apps. Create your own apps for iPhone and Mac!',
    categorySlug: 'programming-languages',
    ageGroup: 'advanced',
    type: 'programming',
    hasCertification: true,
    imagePrompt: 'Swift bird logo with iPhone mockup showing a colorful app, Apple ecosystem icons, flat design for senior students, no text',
    tags: ['swift', 'ios', 'swiftui', 'apple', 'age-15-18'],
    sections: [
      {
        title: 'Swift Language Basics',
        lessons: [
          { title: 'Introduction to Swift', topic: 'Swift overview, Xcode setup, Playgrounds, Swift vs Objective-C', order: 1, includesCode: true, programmingLanguage: 'swift' },
          { title: 'Swift Types and Optionals', topic: 'Value types, reference types, Optional, guard, if let', order: 2, includesCode: true, programmingLanguage: 'swift' },
          { title: 'Functions and Closures in Swift', topic: 'Function syntax, trailing closures, @escaping, capture list', order: 3, includesCode: true, programmingLanguage: 'swift' },
          { title: 'Structs vs Classes in Swift', topic: 'Value vs reference semantics, protocols, extensions', order: 4, includesCode: true, programmingLanguage: 'swift' },
        ],
        quizzes: [{ title: 'Swift Basics Quiz', order: 1, questionCount: 8 }],
      },
      {
        title: 'SwiftUI App Building',
        lessons: [
          { title: 'SwiftUI Fundamentals', topic: 'Declarative UI, View protocol, VStack/HStack/ZStack', order: 5, includesCode: true, programmingLanguage: 'swift' },
          { title: 'State, Binding and ObservableObject', topic: '@State, @Binding, @StateObject, @ObservedObject', order: 6, includesCode: true, programmingLanguage: 'swift' },
          { title: 'Lists, Navigation and Sheets', topic: 'List, NavigationView, NavigationLink, sheet presentation', order: 7, includesCode: true, programmingLanguage: 'swift' },
          { title: 'Networking: URLSession & Codable', topic: 'Fetching JSON data, Codable protocol, async/await in Swift', order: 8, includesCode: true, programmingLanguage: 'swift' },
          { title: 'Persistence with UserDefaults & CoreData', topic: 'Storing user data, CoreData basics, SwiftData introduction', order: 9, includesCode: true, programmingLanguage: 'swift' },
        ],
        quizzes: [],
      },
      {
        title: 'App Store Projects',
        lessons: [
          { title: 'App Store Guidelines & Design Principles', topic: 'Human Interface Guidelines, App Store review process, best practices', order: 10 },
          { title: 'Project: Weather App', topic: 'Full weather app with API, beautiful SwiftUI UI', order: 11, includesCode: true, programmingLanguage: 'swift' },
          { title: 'Project: Habit Tracker App', topic: 'Habit tracking app with persistence, notifications, animations', order: 12, includesCode: true, programmingLanguage: 'swift' },
        ],
        quizzes: [{ title: 'Swift iOS Certificate', order: 2, questionCount: 12 }],
      },
    ],
  },
];
